
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace GameConfig
{
public partial class Tables
{
    /// <summary>
    /// 武器表
    /// </summary>
    public cfg.TbWeapon TbWeapon {get; }
    /// <summary>
    /// 关卡表
    /// </summary>
    public cfg.TbLevel TbLevel {get; }
    /// <summary>
    /// 道具表
    /// </summary>
    public cfg.TbItem TbItem {get; }
    /// <summary>
    /// 玩家属性表
    /// </summary>
    public cfg.TbPlayer TbPlayer {get; }
    /// <summary>
    /// 敌人属性表
    /// </summary>
    public cfg.TbEnemy TbEnemy {get; }
    /// <summary>
    /// 波次表
    /// </summary>
    public cfg.TbWave TbWave {get; }
    /// <summary>
    /// 掉落表
    /// </summary>
    public cfg.TbDrop TbDrop {get; }
    /// <summary>
    /// Buff表
    /// </summary>
    public cfg.TbBuff TbBuff {get; }
    /// <summary>
    /// 传送门表
    /// </summary>
    public cfg.TbPortal TbPortal {get; }
    /// <summary>
    /// 背包容量表
    /// </summary>
    public cfg.TbInventoryConfig TbInventoryConfig {get; }
    /// <summary>
    /// 相机配置
    /// </summary>
    public cfg.TbCamera TbCamera {get; }
    /// <summary>
    /// 弹道全局配置
    /// </summary>
    public cfg.TbBallistic TbBallistic {get; }
    /// <summary>
    /// UI全局配置
    /// </summary>
    public cfg.TbUiConfig TbUiConfig {get; }
    /// <summary>
    /// 拾取物配置
    /// </summary>
    public cfg.TbPickup TbPickup {get; }
    /// <summary>
    /// 建筑表
    /// </summary>
    public cfg.TbBuilding TbBuilding {get; }
    /// <summary>
    /// 生产配方表
    /// </summary>
    public cfg.TbProduction TbProduction {get; }
    /// <summary>
    /// 订单表
    /// </summary>
    public cfg.TbOrder TbOrder {get; }
    /// <summary>
    /// 经营时间配置
    /// </summary>
    public cfg.TbSimTimeConfig TbSimTimeConfig {get; }
    /// <summary>
    /// 3D摄像机配置
    /// </summary>
    public cfg.TbCamera3D TbCamera3D {get; }
    /// <summary>
    /// 容器掉落表
    /// </summary>
    public cfg.TbLootContainer TbLootContainer {get; }
    /// <summary>
    /// 小纸条表
    /// </summary>
    public cfg.TbNote TbNote {get; }
    /// <summary>
    /// 玩家等级经验表
    /// </summary>
    public cfg.TbPlayerLevel TbPlayerLevel {get; }
    /// <summary>
    /// 内容解锁表
    /// </summary>
    public cfg.TbUnlock TbUnlock {get; }
    /// <summary>
    /// NPC表
    /// </summary>
    public cfg.TbNpc TbNpc {get; }
    /// <summary>
    /// 对话头表
    /// </summary>
    public cfg.TbDialogue TbDialogue {get; }
    /// <summary>
    /// 对话节点表
    /// </summary>
    public cfg.TbDialogueNode TbDialogueNode {get; }
    /// <summary>
    /// 任务表
    /// </summary>
    public cfg.TbQuest TbQuest {get; }
    /// <summary>
    /// 任务目标表
    /// </summary>
    public cfg.TbQuestObjective TbQuestObjective {get; }
    /// <summary>
    /// 本地化词条表
    /// </summary>
    public cfg.TbLocalization TbLocalization {get; }
    /// <summary>
    /// 队友人设卡
    /// </summary>
    public cfg.TbCompanion TbCompanion {get; }
    /// <summary>
    /// 队友本地台词表
    /// </summary>
    public cfg.TbCompanionBark TbCompanionBark {get; }
    public cfg.TbAudio TbAudio {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbWeapon = new cfg.TbWeapon(loader("cfg_tbweapon"));
        TbLevel = new cfg.TbLevel(loader("cfg_tblevel"));
        TbItem = new cfg.TbItem(loader("cfg_tbitem"));
        TbPlayer = new cfg.TbPlayer(loader("cfg_tbplayer"));
        TbEnemy = new cfg.TbEnemy(loader("cfg_tbenemy"));
        TbWave = new cfg.TbWave(loader("cfg_tbwave"));
        TbDrop = new cfg.TbDrop(loader("cfg_tbdrop"));
        TbBuff = new cfg.TbBuff(loader("cfg_tbbuff"));
        TbPortal = new cfg.TbPortal(loader("cfg_tbportal"));
        TbInventoryConfig = new cfg.TbInventoryConfig(loader("cfg_tbinventoryconfig"));
        TbCamera = new cfg.TbCamera(loader("cfg_tbcamera"));
        TbBallistic = new cfg.TbBallistic(loader("cfg_tbballistic"));
        TbUiConfig = new cfg.TbUiConfig(loader("cfg_tbuiconfig"));
        TbPickup = new cfg.TbPickup(loader("cfg_tbpickup"));
        TbBuilding = new cfg.TbBuilding(loader("cfg_tbbuilding"));
        TbProduction = new cfg.TbProduction(loader("cfg_tbproduction"));
        TbOrder = new cfg.TbOrder(loader("cfg_tborder"));
        TbSimTimeConfig = new cfg.TbSimTimeConfig(loader("cfg_tbsimtimeconfig"));
        TbCamera3D = new cfg.TbCamera3D(loader("cfg_tbcamera3d"));
        TbLootContainer = new cfg.TbLootContainer(loader("cfg_tblootcontainer"));
        TbNote = new cfg.TbNote(loader("cfg_tbnote"));
        TbPlayerLevel = new cfg.TbPlayerLevel(loader("cfg_tbplayerlevel"));
        TbUnlock = new cfg.TbUnlock(loader("cfg_tbunlock"));
        TbNpc = new cfg.TbNpc(loader("cfg_tbnpc"));
        TbDialogue = new cfg.TbDialogue(loader("cfg_tbdialogue"));
        TbDialogueNode = new cfg.TbDialogueNode(loader("cfg_tbdialoguenode"));
        TbQuest = new cfg.TbQuest(loader("cfg_tbquest"));
        TbQuestObjective = new cfg.TbQuestObjective(loader("cfg_tbquestobjective"));
        TbLocalization = new cfg.TbLocalization(loader("cfg_tblocalization"));
        TbCompanion = new cfg.TbCompanion(loader("cfg_tbcompanion"));
        TbCompanionBark = new cfg.TbCompanionBark(loader("cfg_tbcompanionbark"));
        TbAudio = new cfg.TbAudio(loader("cfg_tbaudio"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbWeapon.ResolveRef(this);
        TbLevel.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbPlayer.ResolveRef(this);
        TbEnemy.ResolveRef(this);
        TbWave.ResolveRef(this);
        TbDrop.ResolveRef(this);
        TbBuff.ResolveRef(this);
        TbPortal.ResolveRef(this);
        TbInventoryConfig.ResolveRef(this);
        TbCamera.ResolveRef(this);
        TbBallistic.ResolveRef(this);
        TbUiConfig.ResolveRef(this);
        TbPickup.ResolveRef(this);
        TbBuilding.ResolveRef(this);
        TbProduction.ResolveRef(this);
        TbOrder.ResolveRef(this);
        TbSimTimeConfig.ResolveRef(this);
        TbCamera3D.ResolveRef(this);
        TbLootContainer.ResolveRef(this);
        TbNote.ResolveRef(this);
        TbPlayerLevel.ResolveRef(this);
        TbUnlock.ResolveRef(this);
        TbNpc.ResolveRef(this);
        TbDialogue.ResolveRef(this);
        TbDialogueNode.ResolveRef(this);
        TbQuest.ResolveRef(this);
        TbQuestObjective.ResolveRef(this);
        TbLocalization.ResolveRef(this);
        TbCompanion.ResolveRef(this);
        TbCompanionBark.ResolveRef(this);
        TbAudio.ResolveRef(this);
    }
}

}

