
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace GameConfig
{
public partial class Tables
{
    /// <summary>
    /// 武器表
    /// </summary>
    public cfg.TbWeapon TbWeapon {get; }
    /// <summary>
    /// 关卡表
    /// </summary>
    public cfg.TbLevel TbLevel {get; }
    /// <summary>
    /// 道具表
    /// </summary>
    public cfg.TbItem TbItem {get; }
    /// <summary>
    /// 玩家属性表
    /// </summary>
    public cfg.TbPlayer TbPlayer {get; }
    /// <summary>
    /// 敌人属性表
    /// </summary>
    public cfg.TbEnemy TbEnemy {get; }
    /// <summary>
    /// 波次表
    /// </summary>
    public cfg.TbWave TbWave {get; }
    /// <summary>
    /// 掉落表
    /// </summary>
    public cfg.TbDrop TbDrop {get; }
    /// <summary>
    /// Buff表
    /// </summary>
    public cfg.TbBuff TbBuff {get; }
    /// <summary>
    /// 传送门表
    /// </summary>
    public cfg.TbPortal TbPortal {get; }
    /// <summary>
    /// 背包容量表
    /// </summary>
    public cfg.TbInventoryConfig TbInventoryConfig {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbWeapon = new cfg.TbWeapon(loader("cfg_tbweapon"));
        TbLevel = new cfg.TbLevel(loader("cfg_tblevel"));
        TbItem = new cfg.TbItem(loader("cfg_tbitem"));
        TbPlayer = new cfg.TbPlayer(loader("cfg_tbplayer"));
        TbEnemy = new cfg.TbEnemy(loader("cfg_tbenemy"));
        TbWave = new cfg.TbWave(loader("cfg_tbwave"));
        TbDrop = new cfg.TbDrop(loader("cfg_tbdrop"));
        TbBuff = new cfg.TbBuff(loader("cfg_tbbuff"));
        TbPortal = new cfg.TbPortal(loader("cfg_tbportal"));
        TbInventoryConfig = new cfg.TbInventoryConfig(loader("cfg_tbinventoryconfig"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbWeapon.ResolveRef(this);
        TbLevel.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbPlayer.ResolveRef(this);
        TbEnemy.ResolveRef(this);
        TbWave.ResolveRef(this);
        TbDrop.ResolveRef(this);
        TbBuff.ResolveRef(this);
        TbPortal.ResolveRef(this);
        TbInventoryConfig.ResolveRef(this);
    }
}

}

