
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig
{

public partial struct vector2int
{
    public vector2int(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        X = (int)_obj.GetValue("x");
        Y = (int)_obj.GetValue("y");
    }

    public static vector2int Deserializevector2int(JToken _buf)
    {
        return new vector2int(_buf);
    }

    public readonly int X;
    public readonly int Y;



    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "x:" + X + ","
        + "y:" + Y + ","
        + "}";
    }
}
}

