
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig
{

public partial struct vector3int
{
    public vector3int(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        X = (int)_obj.GetValue("x");
        Y = (int)_obj.GetValue("y");
        Z = (int)_obj.GetValue("z");
    }

    public static vector3int Deserializevector3int(JToken _buf)
    {
        return new vector3int(_buf);
    }

    public readonly int X;
    public readonly int Y;
    public readonly int Z;



    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "x:" + X + ","
        + "y:" + Y + ","
        + "z:" + Z + ","
        + "}";
    }
}
}

