
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 音频条目
/// </summary>

public sealed partial class Audio : Luban.BeanBase
{
    public Audio(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        AudioType = (string)_obj.GetValue("audioType");
        Volume = (float)_obj.GetValue("volume");
        Loop = (bool)_obj.GetValue("loop");
        Spatial = (bool)_obj.GetValue("spatial");
        MinDist = (float)_obj.GetValue("minDist");
        MaxDist = (float)_obj.GetValue("maxDist");
        SceneKey = (string)_obj.GetValue("sceneKey");
    }

    public static Audio DeserializeAudio(JToken _buf)
    {
        return new cfg.Audio(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly string AudioType;
    public readonly float Volume;
    public readonly bool Loop;
    public readonly bool Spatial;
    public readonly float MinDist;
    public readonly float MaxDist;
    public readonly string SceneKey;


    public const int __ID__ = 1427783084;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "audioType:" + AudioType + ","
        + "volume:" + Volume + ","
        + "loop:" + Loop + ","
        + "spatial:" + Spatial + ","
        + "minDist:" + MinDist + ","
        + "maxDist:" + MaxDist + ","
        + "sceneKey:" + SceneKey + ","
        + "}";
    }
}
}

