
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cfg
{ 
    /// <summary>
    /// 弹道类型
    /// </summary>
    public enum BallisticType
    {
        /// <summary>
        /// 射线即时命中
        /// </summary>
        Raycast = 0,
        /// <summary>
        /// 投掷物
        /// </summary>
        Projectile = 1,
    }

} 

