
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 弹道全局配置
/// </summary>

public sealed partial class Ballistic : Luban.BeanBase
{
    public Ballistic(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        TracerRadius = (float)_obj.GetValue("tracerRadius");
        TracerStartWidth = (float)_obj.GetValue("tracerStartWidth");
        TracerEndWidth = (float)_obj.GetValue("tracerEndWidth");
        TracerTailLength = (float)_obj.GetValue("tracerTailLength");
        MaxActiveTracers = (int)_obj.GetValue("maxActiveTracers");
        HitLayers = (string)_obj.GetValue("hitLayers");
        TracerStartColor = global::GameConfig.cfg.Color.DeserializeColor(_obj.GetValue("tracerStartColor"));
        TracerEndColor = global::GameConfig.cfg.Color.DeserializeColor(_obj.GetValue("tracerEndColor"));
    }

    public static Ballistic DeserializeBallistic(JToken _buf)
    {
        return new cfg.Ballistic(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Tracer射线检测半径
    /// </summary>
    public readonly float TracerRadius;
    /// <summary>
    /// Tracer起始宽度
    /// </summary>
    public readonly float TracerStartWidth;
    /// <summary>
    /// Tracer结束宽度
    /// </summary>
    public readonly float TracerEndWidth;
    /// <summary>
    /// Tracer尾迹长度
    /// </summary>
    public readonly float TracerTailLength;
    /// <summary>
    /// 最大同时存在Tracer数量
    /// </summary>
    public readonly int MaxActiveTracers;
    /// <summary>
    /// 默认命中层级
    /// </summary>
    public readonly string HitLayers;
    /// <summary>
    /// Tracer起始颜色
    /// </summary>
    public readonly cfg.Color TracerStartColor;
    /// <summary>
    /// Tracer结束颜色
    /// </summary>
    public readonly cfg.Color TracerEndColor;


    public const int __ID__ = 2100000002;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        TracerStartColor?.ResolveRef(tables);
        TracerEndColor?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "tracerradius:" + TracerRadius + ","
        + "tracerstartwidth:" + TracerStartWidth + ","
        + "tracerendwidth:" + TracerEndWidth + ","
        + "tracertaillength:" + TracerTailLength + ","
        + "maxactivetracers:" + MaxActiveTracers + ","
        + "hitlayers:" + HitLayers + ","
        + "tracerstartcolor:" + TracerStartColor + ","
        + "tracerendcolor:" + TracerEndColor + ""
        + "}";
    }
}
}
