
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// Buff配置
/// </summary>

public sealed partial class Buff : Luban.BeanBase
{
    public Buff(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Duration = (float)_obj.GetValue("duration");
        EffectType = (int)_obj.GetValue("effectType");
        Value = (float)_obj.GetValue("value");
        Icon = (string)_obj.GetValue("icon");
    }

    public static Buff DeserializeBuff(JToken _buf)
    {
        return new cfg.Buff(_buf);
    }

    /// <summary>
    /// BuffID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly int EffectType;
    /// <summary>
    /// 数值
    /// </summary>
    public readonly float Value;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;


    public const int __ID__ = -231007299;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "duration:" + Duration + ","
        + "effectType:" + EffectType + ","
        + "value:" + Value + ","
        + "icon:" + Icon + ","
        + "}";
    }
}
}

