
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 建筑配置
/// </summary>

public sealed partial class Building : Luban.BeanBase
{
    public Building(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Desc = (string)_obj.GetValue("desc");
        BuildingType = (cfg.EBuildingType)(int)_obj.GetValue("buildingType");
        Icon = (string)_obj.GetValue("icon");
        MaxLevel = (int)_obj.GetValue("maxLevel");
        BuildCostGold = (int)_obj.GetValue("buildCostGold");
        { var __json0 = _obj.GetValue("buildCostItems"); BuildCostItems = new System.Collections.Generic.List<cfg.ItemExchange>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { cfg.ItemExchange __v0;  __v0 = global::GameConfig.cfg.ItemExchange.DeserializeItemExchange(__e0);  BuildCostItems.Add(__v0); }   }
        BuildTime = (float)_obj.GetValue("buildTime");
        UpgradeCostGold = (int)_obj.GetValue("upgradeCostGold");
        { var __json0 = _obj.GetValue("upgradeCostItems"); UpgradeCostItems = new System.Collections.Generic.List<cfg.ItemExchange>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { cfg.ItemExchange __v0;  __v0 = global::GameConfig.cfg.ItemExchange.DeserializeItemExchange(__e0);  UpgradeCostItems.Add(__v0); }   }
        UpgradeTime = (float)_obj.GetValue("upgradeTime");
        ProductionSlotCount = (int)_obj.GetValue("productionSlotCount");
        UnlockLevel = (int)_obj.GetValue("unlockLevel");
    }

    public static Building DeserializeBuilding(JToken _buf)
    {
        return new cfg.Building(_buf);
    }

    /// <summary>
    /// 建筑ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 建筑类型
    /// </summary>
    public readonly cfg.EBuildingType BuildingType;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 最大等级
    /// </summary>
    public readonly int MaxLevel;
    /// <summary>
    /// 建造金币
    /// </summary>
    public readonly int BuildCostGold;
    /// <summary>
    /// 建造材料
    /// </summary>
    public readonly System.Collections.Generic.List<cfg.ItemExchange> BuildCostItems;
    /// <summary>
    /// 建造耗时
    /// </summary>
    public readonly float BuildTime;
    /// <summary>
    /// 升级金币
    /// </summary>
    public readonly int UpgradeCostGold;
    /// <summary>
    /// 升级材料
    /// </summary>
    public readonly System.Collections.Generic.List<cfg.ItemExchange> UpgradeCostItems;
    /// <summary>
    /// 升级耗时
    /// </summary>
    public readonly float UpgradeTime;
    /// <summary>
    /// 生产槽位
    /// </summary>
    public readonly int ProductionSlotCount;
    /// <summary>
    /// 解锁等级
    /// </summary>
    public readonly int UnlockLevel;


    public const int __ID__ = -381740770;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in BuildCostItems) { _e?.ResolveRef(tables); }
        foreach (var _e in UpgradeCostItems) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "buildingType:" + BuildingType + ","
        + "icon:" + Icon + ","
        + "maxLevel:" + MaxLevel + ","
        + "buildCostGold:" + BuildCostGold + ","
        + "buildCostItems:" + Luban.StringUtil.CollectionToString(BuildCostItems) + ","
        + "buildTime:" + BuildTime + ","
        + "upgradeCostGold:" + UpgradeCostGold + ","
        + "upgradeCostItems:" + Luban.StringUtil.CollectionToString(UpgradeCostItems) + ","
        + "upgradeTime:" + UpgradeTime + ","
        + "productionSlotCount:" + ProductionSlotCount + ","
        + "unlockLevel:" + UnlockLevel + ","
        + "}";
    }
}
}

