
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 3D摄像机配置
/// </summary>

public sealed partial class Camera3D : Luban.BeanBase
{
    public Camera3D(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        PitchAngle = (float)_obj.GetValue("pitchAngle");
        InitialHeight = (float)_obj.GetValue("initialHeight");
        InitialDistance = (float)_obj.GetValue("initialDistance");
        Fov = (float)_obj.GetValue("fov");
        MinZoom = (float)_obj.GetValue("minZoom");
        MaxZoom = (float)_obj.GetValue("maxZoom");
        MoveSpeed = (float)_obj.GetValue("moveSpeed");
        ZoomSpeed = (float)_obj.GetValue("zoomSpeed");
        MaxRotationAngle = (float)_obj.GetValue("maxRotationAngle");
        RotationSpeed = (float)_obj.GetValue("rotationSpeed");
        FollowSmoothTime = (float)_obj.GetValue("followSmoothTime");
    }

    public static Camera3D DeserializeCamera3D(JToken _buf)
    {
        return new cfg.Camera3D(_buf);
    }

    /// <summary>
    /// 配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 俯视角度
    /// </summary>
    public readonly float PitchAngle;
    /// <summary>
    /// 初始高度
    /// </summary>
    public readonly float InitialHeight;
    /// <summary>
    /// 初始距离
    /// </summary>
    public readonly float InitialDistance;
    /// <summary>
    /// 视场角
    /// </summary>
    public readonly float Fov;
    /// <summary>
    /// 最小缩放
    /// </summary>
    public readonly float MinZoom;
    /// <summary>
    /// 最大缩放
    /// </summary>
    public readonly float MaxZoom;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 缩放速度
    /// </summary>
    public readonly float ZoomSpeed;
    /// <summary>
    /// 最大旋转角度
    /// </summary>
    public readonly float MaxRotationAngle;
    /// <summary>
    /// 旋转速度
    /// </summary>
    public readonly float RotationSpeed;
    /// <summary>
    /// 跟随平滑时间
    /// </summary>
    public readonly float FollowSmoothTime;


    public const int __ID__ = 899324608;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "pitchAngle:" + PitchAngle + ","
        + "initialHeight:" + InitialHeight + ","
        + "initialDistance:" + InitialDistance + ","
        + "fov:" + Fov + ","
        + "minZoom:" + MinZoom + ","
        + "maxZoom:" + MaxZoom + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "zoomSpeed:" + ZoomSpeed + ","
        + "maxRotationAngle:" + MaxRotationAngle + ","
        + "rotationSpeed:" + RotationSpeed + ","
        + "followSmoothTime:" + FollowSmoothTime + ","
        + "}";
    }
}
}

