
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 相机配置
/// </summary>

public sealed partial class Camera : Luban.BeanBase
{
    public Camera(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        SmoothTime = (float)_obj.GetValue("smoothTime");
        DefaultFov = (float)_obj.GetValue("defaultFov");
        FovSmoothTime = (float)_obj.GetValue("fovSmoothTime");
        ShakeDamping = (float)_obj.GetValue("shakeDamping");
        ScopeRenderSize = (int)_obj.GetValue("scopeRenderSize");
        ScopeCameraFov = (float)_obj.GetValue("scopeCameraFov");
        DefaultOrthographicSize = (float)_obj.GetValue("defaultOrthographicSize");
    }

    public static Camera DeserializeCamera(JToken _buf)
    {
        return new cfg.Camera(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 相机平滑时间
    /// </summary>
    public readonly float SmoothTime;
    /// <summary>
    /// 默认FOV
    /// </summary>
    public readonly float DefaultFov;
    /// <summary>
    /// FOV平滑时间
    /// </summary>
    public readonly float FovSmoothTime;
    /// <summary>
    /// 震动衰减速度
    /// </summary>
    public readonly float ShakeDamping;
    /// <summary>
    /// 狙击镜渲染纹理尺寸
    /// </summary>
    public readonly int ScopeRenderSize;
    /// <summary>
    /// 狙击镜相机FOV
    /// </summary>
    public readonly float ScopeCameraFov;
    /// <summary>
    /// 默认正交尺寸
    /// </summary>
    public readonly float DefaultOrthographicSize;


    public const int __ID__ = 2100000001;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "smoothtime:" + SmoothTime + ","
        + "defaultfov:" + DefaultFov + ","
        + "fovsmoothtime:" + FovSmoothTime + ","
        + "shakedamping:" + ShakeDamping + ","
        + "scoperendersize:" + ScopeRenderSize + ","
        + "scopecamerafov:" + ScopeCameraFov + ","
        + "defaultorthographicsize:" + DefaultOrthographicSize + ""
        + "}";
    }
}
}
