
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 颜色
/// </summary>

public sealed partial class Color : Luban.BeanBase
{
    public Color(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        R = (float)_obj.GetValue("r");
        G = (float)_obj.GetValue("g");
        B = (float)_obj.GetValue("b");
        A = (float)_obj.GetValue("a");
    }

    public static Color DeserializeColor(JToken _buf)
    {
        return new cfg.Color(_buf);
    }

    /// <summary>
    /// 红
    /// </summary>
    public readonly float R;
    /// <summary>
    /// 绿
    /// </summary>
    public readonly float G;
    /// <summary>
    /// 蓝
    /// </summary>
    public readonly float B;
    /// <summary>
    /// 透明度
    /// </summary>
    public readonly float A;


    public const int __ID__ = 1429459257;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "r:" + R + ","
        + "g:" + G + ","
        + "b:" + B + ","
        + "a:" + A + ","
        + "}";
    }
}
}

