
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 队友人设卡
/// </summary>

public sealed partial class Companion : Luban.BeanBase
{
    public Companion(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        NameKey = (string)_obj.GetValue("nameKey");
        PersonaPrompt = (string)_obj.GetValue("personaPrompt");
        WeaponConfigId = (int)_obj.GetValue("weaponConfigId");
        MaxHp = (int)_obj.GetValue("maxHp");
        MoveSpeed = (float)_obj.GetValue("moveSpeed");
        FollowStopDist = (float)_obj.GetValue("followStopDist");
        EngageMinDist = (float)_obj.GetValue("engageMinDist");
        RetreatHpRatio = (float)_obj.GetValue("retreatHpRatio");
        IdleChatMinInterval = (float)_obj.GetValue("idleChatMinInterval");
        IdleChatMaxInterval = (float)_obj.GetValue("idleChatMaxInterval");
        LlmRequestInterval = (float)_obj.GetValue("llmRequestInterval");
        LlmBudgetPerRun = (int)_obj.GetValue("llmBudgetPerRun");
        LlmTimeout = (float)_obj.GetValue("llmTimeout");
        IntentTtl = (float)_obj.GetValue("intentTtl");
        OfflineProbeInterval = (float)_obj.GetValue("offlineProbeInterval");
        DecisionIntervalSafe = (float)_obj.GetValue("decisionIntervalSafe");
        DecisionIntervalCombat = (float)_obj.GetValue("decisionIntervalCombat");
        DecisionTimeout = (float)_obj.GetValue("decisionTimeout");
        ControlBudgetPerRun = (int)_obj.GetValue("controlBudgetPerRun");
        ProactiveEngageDist = (float)_obj.GetValue("proactiveEngageDist");
        ConversationHold = (float)_obj.GetValue("conversationHold");
        PostCombatCalm = (float)_obj.GetValue("postCombatCalm");
        DirHintInterval = (float)_obj.GetValue("dirHintInterval");
        OfflineFailThreshold = (int)_obj.GetValue("offlineFailThreshold");
        DecisionSayInterval = (float)_obj.GetValue("decisionSayInterval");
        MaxReportEntries = (int)_obj.GetValue("maxReportEntries");
        LeashDist = (float)_obj.GetValue("leashDist");
        LeashStopDist = (float)_obj.GetValue("leashStopDist");
        SpawnOffsetX = (float)_obj.GetValue("spawnOffsetX");
        SpawnOffsetZ = (float)_obj.GetValue("spawnOffsetZ");
    }

    public static Companion DeserializeCompanion(JToken _buf)
    {
        return new cfg.Companion(_buf);
    }

    /// <summary>
    /// 队友ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 呼号本地化键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// LLM 人设 system prompt(英文)
    /// </summary>
    public readonly string PersonaPrompt;
    /// <summary>
    /// 持有武器
    /// </summary>
    public readonly int WeaponConfigId;
    /// <summary>
    /// 最大HP
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 跟随到位距离
    /// </summary>
    public readonly float FollowStopDist;
    /// <summary>
    /// 最小交战距离
    /// </summary>
    public readonly float EngageMinDist;
    /// <summary>
    /// 撤退血量比例
    /// </summary>
    public readonly float RetreatHpRatio;
    /// <summary>
    /// 安全闲聊最小间隔s
    /// </summary>
    public readonly float IdleChatMinInterval;
    /// <summary>
    /// 安全闲聊最大间隔s
    /// </summary>
    public readonly float IdleChatMaxInterval;
    /// <summary>
    /// LLM 全局最小请求间隔s
    /// </summary>
    public readonly float LlmRequestInterval;
    /// <summary>
    /// 单局 LLM 请求限额
    /// </summary>
    public readonly int LlmBudgetPerRun;
    /// <summary>
    /// LLM 超时s
    /// </summary>
    public readonly float LlmTimeout;
    /// <summary>
    /// 意图 TTL s
    /// </summary>
    public readonly float IntentTtl;
    /// <summary>
    /// 离线恢复探测间隔s
    /// </summary>
    public readonly float OfflineProbeInterval;
    /// <summary>
    /// 安全决策间隔s(M5)
    /// </summary>
    public readonly float DecisionIntervalSafe;
    /// <summary>
    /// 战斗决策间隔s(M5)
    /// </summary>
    public readonly float DecisionIntervalCombat;
    /// <summary>
    /// 决策响应超时s(M5)
    /// </summary>
    public readonly float DecisionTimeout;
    /// <summary>
    /// 单局操控决策限额(M5)
    /// </summary>
    public readonly int ControlBudgetPerRun;
    /// <summary>
    /// 主动开火警戒半径m
    /// </summary>
    public readonly float ProactiveEngageDist;
    public readonly float ConversationHold;
    public readonly float PostCombatCalm;
    public readonly float DirHintInterval;
    public readonly int OfflineFailThreshold;
    public readonly float DecisionSayInterval;
    public readonly int MaxReportEntries;
    public readonly float LeashDist;
    public readonly float LeashStopDist;
    public readonly float SpawnOffsetX;
    public readonly float SpawnOffsetZ;


    public const int __ID__ = 1038461410;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "personaPrompt:" + PersonaPrompt + ","
        + "weaponConfigId:" + WeaponConfigId + ","
        + "maxHp:" + MaxHp + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "followStopDist:" + FollowStopDist + ","
        + "engageMinDist:" + EngageMinDist + ","
        + "retreatHpRatio:" + RetreatHpRatio + ","
        + "idleChatMinInterval:" + IdleChatMinInterval + ","
        + "idleChatMaxInterval:" + IdleChatMaxInterval + ","
        + "llmRequestInterval:" + LlmRequestInterval + ","
        + "llmBudgetPerRun:" + LlmBudgetPerRun + ","
        + "llmTimeout:" + LlmTimeout + ","
        + "intentTtl:" + IntentTtl + ","
        + "offlineProbeInterval:" + OfflineProbeInterval + ","
        + "decisionIntervalSafe:" + DecisionIntervalSafe + ","
        + "decisionIntervalCombat:" + DecisionIntervalCombat + ","
        + "decisionTimeout:" + DecisionTimeout + ","
        + "controlBudgetPerRun:" + ControlBudgetPerRun + ","
        + "proactiveEngageDist:" + ProactiveEngageDist + ","
        + "conversationHold:" + ConversationHold + ","
        + "postCombatCalm:" + PostCombatCalm + ","
        + "dirHintInterval:" + DirHintInterval + ","
        + "offlineFailThreshold:" + OfflineFailThreshold + ","
        + "decisionSayInterval:" + DecisionSayInterval + ","
        + "maxReportEntries:" + MaxReportEntries + ","
        + "leashDist:" + LeashDist + ","
        + "leashStopDist:" + LeashStopDist + ","
        + "spawnOffsetX:" + SpawnOffsetX + ","
        + "spawnOffsetZ:" + SpawnOffsetZ + ","
        + "}";
    }
}
}

