
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 好感获取规则表
/// </summary>

public sealed partial class CompanionAffinityGain : Luban.BeanBase
{
    public CompanionAffinityGain(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Source = (string)_obj.GetValue("source");
        Value = (int)_obj.GetValue("value");
        CooldownSec = (float)_obj.GetValue("cooldownSec");
        PerRunCap = (int)_obj.GetValue("perRunCap");
    }

    public static CompanionAffinityGain DeserializeCompanionAffinityGain(JToken _buf)
    {
        return new cfg.CompanionAffinityGain(_buf);
    }

    /// <summary>
    /// 来源标识(chat/extract/protect)
    /// </summary>
    public readonly string Source;
    /// <summary>
    /// 好感数值
    /// </summary>
    public readonly int Value;
    /// <summary>
    /// 冷却秒(0=无)
    /// </summary>
    public readonly float CooldownSec;
    /// <summary>
    /// 每局上限(0=无限制)
    /// </summary>
    public readonly int PerRunCap;


    public const int __ID__ = 735530953;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "source:" + Source + ","
        + "value:" + Value + ","
        + "cooldownSec:" + CooldownSec + ","
        + "perRunCap:" + PerRunCap + ","
        + "}";
    }
}
}

