
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 队友记忆规则表
/// </summary>

public sealed partial class CompanionMemoryRule : Luban.BeanBase
{
    public CompanionMemoryRule(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        MemoryType = (string)_obj.GetValue("memoryType");
        MinTier = (int)_obj.GetValue("minTier");
        MaxCount = (int)_obj.GetValue("maxCount");
        SampleRule = (string)_obj.GetValue("sampleRule");
        WriteChance = (float)_obj.GetValue("writeChance");
    }

    public static CompanionMemoryRule DeserializeCompanionMemoryRule(JToken _buf)
    {
        return new cfg.CompanionMemoryRule(_buf);
    }

    /// <summary>
    /// 规则ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 记忆类型
    /// </summary>
    public readonly string MemoryType;
    /// <summary>
    /// 生效最低档位
    /// </summary>
    public readonly int MinTier;
    /// <summary>
    /// 容量上限
    /// </summary>
    public readonly int MaxCount;
    /// <summary>
    /// 采样规则(fifo/random_forget/random_evict)
    /// </summary>
    public readonly string SampleRule;
    /// <summary>
    /// 写入概率(0-1)
    /// </summary>
    public readonly float WriteChance;


    public const int __ID__ = 1018131231;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "memoryType:" + MemoryType + ","
        + "minTier:" + MinTier + ","
        + "maxCount:" + MaxCount + ","
        + "sampleRule:" + SampleRule + ","
        + "writeChance:" + WriteChance + ","
        + "}";
    }
}
}

