
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 好感档位表
/// </summary>

public sealed partial class CompanionAffinityTier : Luban.BeanBase
{
    public CompanionAffinityTier(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Tier = (int)_obj.GetValue("tier");
        NameKey = (string)_obj.GetValue("nameKey");
        Threshold = (int)_obj.GetValue("threshold");
        DescKey = (string)_obj.GetValue("descKey");
    }

    public static CompanionAffinityTier DeserializeCompanionAffinityTier(JToken _buf)
    {
        return new cfg.CompanionAffinityTier(_buf);
    }

    /// <summary>
    /// 档位(1-4)
    /// </summary>
    public readonly int Tier;
    /// <summary>
    /// 档位名词条键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 到达该档所需累计好感
    /// </summary>
    public readonly int Threshold;
    /// <summary>
    /// 档位人格描述词条键
    /// </summary>
    public readonly string DescKey;


    public const int __ID__ = 735925804;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "tier:" + Tier + ","
        + "nameKey:" + NameKey + ","
        + "threshold:" + Threshold + ","
        + "descKey:" + DescKey + ","
        + "}";
    }
}
}

