
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 队友分档人格提示表
/// </summary>

public sealed partial class CompanionPersona : Luban.BeanBase
{
    public CompanionPersona(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        CompanionId = (int)_obj.GetValue("companionId");
        Tier = (int)_obj.GetValue("tier");
        PromptAdd = (string)_obj.GetValue("promptAdd");
    }

    public static CompanionPersona DeserializeCompanionPersona(JToken _buf)
    {
        return new cfg.CompanionPersona(_buf);
    }

    /// <summary>
    /// 唯一ID(companionId*10+tier)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 队友ID
    /// </summary>
    public readonly int CompanionId;
    /// <summary>
    /// 好感档位
    /// </summary>
    public readonly int Tier;
    /// <summary>
    /// 追加给LLM的关系姿态文本(英文)
    /// </summary>
    public readonly string PromptAdd;


    public const int __ID__ = -592692374;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "companionId:" + CompanionId + ","
        + "tier:" + Tier + ","
        + "promptAdd:" + PromptAdd + ","
        + "}";
    }
}
}

