
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 队友本地台词
/// </summary>

public sealed partial class CompanionBark : Luban.BeanBase
{
    public CompanionBark(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Trigger = (string)_obj.GetValue("trigger");
        TextKey = (string)_obj.GetValue("textKey");
        Weight = (int)_obj.GetValue("weight");
        Cooldown = (float)_obj.GetValue("cooldown");
        MinTier = (int)_obj.GetValue("minTier");
    }

    public static CompanionBark DeserializeCompanionBark(JToken _buf)
    {
        return new cfg.CompanionBark(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 触发键
    /// </summary>
    public readonly string Trigger;
    /// <summary>
    /// 台词本地化键
    /// </summary>
    public readonly string TextKey;
    /// <summary>
    /// 随机权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 单键冷却s(0=不限)
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 最低好感档位(1-4)
    /// </summary>
    public readonly int MinTier;


    public const int __ID__ = 494494650;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "trigger:" + Trigger + ","
        + "textKey:" + TextKey + ","
        + "weight:" + Weight + ","
        + "cooldown:" + Cooldown + ","
        + "minTier:" + MinTier + ","
        + "}";
    }
}
}

