
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 对话头
/// </summary>

public sealed partial class Dialogue : Luban.BeanBase
{
    public Dialogue(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        StartNode = (int)_obj.GetValue("startNode");
        OnceOnly = (bool)_obj.GetValue("onceOnly");
        Priority = (int)_obj.GetValue("priority");
    }

    public static Dialogue DeserializeDialogue(JToken _buf)
    {
        return new cfg.Dialogue(_buf);
    }

    /// <summary>
    /// 对话ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 注释名(不显示)
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 起始节点ID
    /// </summary>
    public readonly int StartNode;
    /// <summary>
    /// 只触发一次
    /// </summary>
    public readonly bool OnceOnly;
    /// <summary>
    /// 优先级(大优先)
    /// </summary>
    public readonly int Priority;


    public const int __ID__ = 815063106;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "startNode:" + StartNode + ","
        + "onceOnly:" + OnceOnly + ","
        + "priority:" + Priority + ","
        + "}";
    }
}
}

