
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 对话节点
/// </summary>

public sealed partial class DialogueNode : Luban.BeanBase
{
    public DialogueNode(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        DialogueId = (int)_obj.GetValue("dialogueId");
        Type = (string)_obj.GetValue("type");
        Speaker = (string)_obj.GetValue("speaker");
        Text = (string)_obj.GetValue("text");
        Choices = (string)_obj.GetValue("choices");
        Condition = (string)_obj.GetValue("condition");
        Action = (string)_obj.GetValue("action");
        Next = (int)_obj.GetValue("next");
    }

    public static DialogueNode DeserializeDialogueNode(JToken _buf)
    {
        return new cfg.DialogueNode(_buf);
    }

    /// <summary>
    /// 节点ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属对话
    /// </summary>
    public readonly int DialogueId;
    /// <summary>
    /// 类型(line/choice/setflag/end)
    /// </summary>
    public readonly string Type;
    /// <summary>
    /// 说话人
    /// </summary>
    public readonly string Speaker;
    /// <summary>
    /// 正文
    /// </summary>
    public readonly string Text;
    /// <summary>
    /// 选项(文本-&gt;节点|...)
    /// </summary>
    public readonly string Choices;
    /// <summary>
    /// 进入条件
    /// </summary>
    public readonly string Condition;
    /// <summary>
    /// 到达动作
    /// </summary>
    public readonly string Action;
    /// <summary>
    /// 下一节点(0=结束)
    /// </summary>
    public readonly int Next;


    public const int __ID__ = 518787428;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "dialogueId:" + DialogueId + ","
        + "type:" + Type + ","
        + "speaker:" + Speaker + ","
        + "text:" + Text + ","
        + "choices:" + Choices + ","
        + "condition:" + Condition + ","
        + "action:" + Action + ","
        + "next:" + Next + ","
        + "}";
    }
}
}

