
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 掉落配置
/// </summary>

public sealed partial class Drop : Luban.BeanBase
{
    public Drop(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        EnemyId = (int)_obj.GetValue("enemyId");
        ItemId = (int)_obj.GetValue("itemId");
        DropRate = (int)_obj.GetValue("dropRate");
        MinCount = (int)_obj.GetValue("minCount");
        MaxCount = (int)_obj.GetValue("maxCount");
    }

    public static Drop DeserializeDrop(JToken _buf)
    {
        return new cfg.Drop(_buf);
    }

    /// <summary>
    /// 掉落ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 敌人ID
    /// </summary>
    public readonly int EnemyId;
    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 掉落概率(万分之一)
    /// </summary>
    public readonly int DropRate;
    /// <summary>
    /// 最小数量
    /// </summary>
    public readonly int MinCount;
    /// <summary>
    /// 最大数量
    /// </summary>
    public readonly int MaxCount;


    public const int __ID__ = -230950311;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "enemyId:" + EnemyId + ","
        + "itemId:" + ItemId + ","
        + "dropRate:" + DropRate + ","
        + "minCount:" + MinCount + ","
        + "maxCount:" + MaxCount + ","
        + "}";
    }
}
}

