
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cfg
{ 
    /// <summary>
    /// 建筑类型
    /// </summary>
    public enum EBuildingType
    {
        /// <summary>
        /// 工坊
        /// </summary>
        Workshop = 0,
        /// <summary>
        /// 农场
        /// </summary>
        Farm = 1,
        /// <summary>
        /// 贸易
        /// </summary>
        Trade = 2,
        /// <summary>
        /// 装饰
        /// </summary>
        Decor = 3,
    }

} 

