
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cfg
{ 
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum EItemType
    {
        /// <summary>
        /// 材料
        /// </summary>
        Material = 0,
        /// <summary>
        /// 消耗品
        /// </summary>
        Consumable = 1,
    }

} 

