
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 敌人属性
/// </summary>

public sealed partial class Enemy : Luban.BeanBase
{
    public Enemy(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        MaxHp = (int)_obj.GetValue("maxHp");
        MoveSpeed = (float)_obj.GetValue("moveSpeed");
        RotationSpeed = (float)_obj.GetValue("rotationSpeed");
        AttackDamage = (int)_obj.GetValue("attackDamage");
        AttackRange = (float)_obj.GetValue("attackRange");
        AttackInterval = (float)_obj.GetValue("attackInterval");
        Prefab = (string)_obj.GetValue("prefab");
    }

    public static Enemy DeserializeEnemy(JToken _buf)
    {
        return new cfg.Enemy(_buf);
    }

    /// <summary>
    /// 敌人ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 最大血量
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 旋转速度
    /// </summary>
    public readonly float RotationSpeed;
    /// <summary>
    /// 攻击伤害
    /// </summary>
    public readonly int AttackDamage;
    /// <summary>
    /// 攻击范围
    /// </summary>
    public readonly float AttackRange;
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public readonly float AttackInterval;
    /// <summary>
    /// 预制体
    /// </summary>
    public readonly string Prefab;


    public const int __ID__ = 1431269726;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "maxHp:" + MaxHp + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "rotationSpeed:" + RotationSpeed + ","
        + "attackDamage:" + AttackDamage + ","
        + "attackRange:" + AttackRange + ","
        + "attackInterval:" + AttackInterval + ","
        + "prefab:" + Prefab + ","
        + "}";
    }
}
}

