
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cfg
{ 
    /// <summary>
    /// 品质
    /// </summary>
    public enum EQuality
    {
        /// <summary>
        /// 蓝色
        /// </summary>
        Blue = 0,
        /// <summary>
        /// 紫色
        /// </summary>
        Purple = 1,
        /// <summary>
        /// 黄色
        /// </summary>
        Yellow = 2,
        /// <summary>
        /// 红色
        /// </summary>
        Red = 3,
    }

} 

