
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cfg
{ 
    /// <summary>
    /// 品质
    /// </summary>
    public enum EQuality
    {
        /// <summary>
        /// 白色
        /// </summary>
        White = 0,
        /// <summary>
        /// 绿色
        /// </summary>
        Green = 1,
        /// <summary>
        /// 蓝色
        /// </summary>
        Blue = 2,
        /// <summary>
        /// 紫色
        /// </summary>
        Purple = 3,
        /// <summary>
        /// 橙色
        /// </summary>
        Orange = 4,
    }

} 

