
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cfg
{ 
    /// <summary>
    /// 技能效果类型
    /// </summary>
    public enum ESkillEffect
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 伤害百分比(每级小数)
        /// </summary>
        DamagePct = 1,
        /// <summary>
        /// 生命上限加算
        /// </summary>
        MaxHpAdd = 2,
        /// <summary>
        /// 耐力上限加算
        /// </summary>
        StaminaMaxAdd = 3,
        /// <summary>
        /// 移速百分比
        /// </summary>
        MoveSpeedPct = 4,
        /// <summary>
        /// 换弹时间缩减百分比
        /// </summary>
        ReloadTimePct = 5,
        /// <summary>
        /// 弹匣容量加算
        /// </summary>
        ClipSizeAdd = 6,
        /// <summary>
        /// 金币获取百分比
        /// </summary>
        GoldGainPct = 7,
        /// <summary>
        /// 经验获取百分比
        /// </summary>
        ExpGainPct = 8,
        /// <summary>
        /// 生产加速百分比
        /// </summary>
        ProductionSpeedPct = 9,
        /// <summary>
        /// 闪避耐力消耗缩减百分比
        /// </summary>
        DodgeCostPct = 10,
    }

} 

