
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cfg
{ 
    /// <summary>
    /// 开火模式
    /// </summary>
    public enum FireMode
    {
        /// <summary>
        /// 单发
        /// </summary>
        Single = 0,
        /// <summary>
        /// 自动
        /// </summary>
        Auto = 1,
    }

} 

