
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 背包容量配置
/// </summary>

public sealed partial class InventoryConfig : Luban.BeanBase
{
    public InventoryConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        TempBagCapacity = (int)_obj.GetValue("tempBagCapacity");
        WarehouseCapacity = (int)_obj.GetValue("warehouseCapacity");
    }

    public static InventoryConfig DeserializeInventoryConfig(JToken _buf)
    {
        return new cfg.InventoryConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 临时背包槽位
    /// </summary>
    public readonly int TempBagCapacity;
    /// <summary>
    /// 仓库槽位
    /// </summary>
    public readonly int WarehouseCapacity;


    public const int __ID__ = 786424340;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "tempBagCapacity:" + TempBagCapacity + ","
        + "warehouseCapacity:" + WarehouseCapacity + ","
        + "}";
    }
}
}

