
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 道具配置
/// </summary>

public sealed partial class Item : Luban.BeanBase
{
    public Item(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Desc = (string)_obj.GetValue("desc");
        Price = (int)_obj.GetValue("price");
        Quality = (cfg.EQuality)(int)_obj.GetValue("quality");
        UpgradeToItemId = (int)_obj.GetValue("upgradeToItemId");
        {if (_obj.TryGetValue("expireTime", out var _j)) { ExpireTime = (long)_j; } else { ExpireTime = null; } }
        BatchUseable = (bool)_obj.GetValue("batchUseable");
        { var __json0 = _obj.GetValue("exchangeList"); ExchangeList = new System.Collections.Generic.List<cfg.ItemExchange>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { cfg.ItemExchange __v0;  __v0 = global::GameConfig.cfg.ItemExchange.DeserializeItemExchange(__e0);  ExchangeList.Add(__v0); }   }
        ItemType = (cfg.EItemType)(int)_obj.GetValue("itemType");
        Icon = (string)_obj.GetValue("icon");
        StackLimit = (int)_obj.GetValue("stackLimit");
    }

    public static Item DeserializeItem(JToken _buf)
    {
        return new cfg.Item(_buf);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly cfg.EQuality Quality;
    /// <summary>
    /// 升级目标道具ID
    /// </summary>
    public readonly int UpgradeToItemId;
    /// <summary>
    /// 过期时间
    /// </summary>
    public readonly long? ExpireTime;
    /// <summary>
    /// 是否可批量使用
    /// </summary>
    public readonly bool BatchUseable;
    /// <summary>
    /// 兑换列表
    /// </summary>
    public readonly System.Collections.Generic.List<cfg.ItemExchange> ExchangeList;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly cfg.EItemType ItemType;
    /// <summary>
    /// 图标资源地址
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 堆叠上限
    /// </summary>
    public readonly int StackLimit;


    public const int __ID__ = -230799747;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in ExchangeList) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "price:" + Price + ","
        + "quality:" + Quality + ","
        + "upgradeToItemId:" + UpgradeToItemId + ","
        + "expireTime:" + ExpireTime + ","
        + "batchUseable:" + BatchUseable + ","
        + "exchangeList:" + Luban.StringUtil.CollectionToString(ExchangeList) + ","
        + "itemType:" + ItemType + ","
        + "icon:" + Icon + ","
        + "stackLimit:" + StackLimit + ","
        + "}";
    }
}
}

