
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 关卡配置
/// </summary>

public sealed partial class Level : Luban.BeanBase
{
    public Level(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        DisplayName = (string)_obj.GetValue("displayName");
        SceneName = (string)_obj.GetValue("sceneName");
        Description = (string)_obj.GetValue("description");
        { var __json0 = _obj.GetValue("defaultWeaponIds"); int _n0 = (__json0 as JArray).Count; DefaultWeaponIds = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  DefaultWeaponIds[__index0++] = __v0; }   }
        PlayerMaxHp = (int)_obj.GetValue("playerMaxHp");
        EnemyCount = (int)_obj.GetValue("enemyCount");
        EnemySpawnRadius = (float)_obj.GetValue("enemySpawnRadius");
        EnemyConfigId = (int)_obj.GetValue("enemyConfigId");
        EnemyMaxHp = (int)_obj.GetValue("enemyMaxHp");
    }

    public static Level DeserializeLevel(JToken _buf)
    {
        return new cfg.Level(_buf);
    }

    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 显示名称
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 场景名
    /// </summary>
    public readonly string SceneName;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 默认武器ID列表
    /// </summary>
    public readonly int[] DefaultWeaponIds;
    /// <summary>
    /// 玩家最大血量
    /// </summary>
    public readonly int PlayerMaxHp;
    /// <summary>
    /// 敌人数量
    /// </summary>
    public readonly int EnemyCount;
    /// <summary>
    /// 敌人刷新半径
    /// </summary>
    public readonly float EnemySpawnRadius;
    /// <summary>
    /// 敌人配置ID
    /// </summary>
    public readonly int EnemyConfigId;
    /// <summary>
    /// 敌人最大血量
    /// </summary>
    public readonly int EnemyMaxHp;


    public const int __ID__ = 1437482330;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "displayName:" + DisplayName + ","
        + "sceneName:" + SceneName + ","
        + "description:" + Description + ","
        + "defaultWeaponIds:" + Luban.StringUtil.CollectionToString(DefaultWeaponIds) + ","
        + "playerMaxHp:" + PlayerMaxHp + ","
        + "enemyCount:" + EnemyCount + ","
        + "enemySpawnRadius:" + EnemySpawnRadius + ","
        + "enemyConfigId:" + EnemyConfigId + ","
        + "enemyMaxHp:" + EnemyMaxHp + ","
        + "}";
    }
}
}

