
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 本地化词条
/// </summary>

public sealed partial class Localization : Luban.BeanBase
{
    public Localization(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Key = (string)_obj.GetValue("key");
        En = (string)_obj.GetValue("en");
        ZhCn = (string)_obj.GetValue("zh_cn");
        ZhTw = (string)_obj.GetValue("zh_tw");
        Ja = (string)_obj.GetValue("ja");
        Ko = (string)_obj.GetValue("ko");
    }

    public static Localization DeserializeLocalization(JToken _buf)
    {
        return new cfg.Localization(_buf);
    }

    /// <summary>
    /// 词条Key
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 英文(必填/兜底)
    /// </summary>
    public readonly string En;
    /// <summary>
    /// 简体中文
    /// </summary>
    public readonly string ZhCn;
    /// <summary>
    /// 繁体中文
    /// </summary>
    public readonly string ZhTw;
    /// <summary>
    /// 日文
    /// </summary>
    public readonly string Ja;
    /// <summary>
    /// 韩文
    /// </summary>
    public readonly string Ko;


    public const int __ID__ = -1644066813;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "en:" + En + ","
        + "zhCn:" + ZhCn + ","
        + "zhTw:" + ZhTw + ","
        + "ja:" + Ja + ","
        + "ko:" + Ko + ","
        + "}";
    }
}
}

