
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 容器掉落记录
/// </summary>

public sealed partial class LootContainer : Luban.BeanBase
{
    public LootContainer(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        ContainerId = (int)_obj.GetValue("containerId");
        ItemId = (int)_obj.GetValue("itemId");
        Weight = (int)_obj.GetValue("weight");
        MinCount = (int)_obj.GetValue("minCount");
        MaxCount = (int)_obj.GetValue("maxCount");
    }

    public static LootContainer DeserializeLootContainer(JToken _buf)
    {
        return new cfg.LootContainer(_buf);
    }

    public readonly int Id;
    public readonly int ContainerId;
    public readonly int ItemId;
    public readonly int Weight;
    public readonly int MinCount;
    public readonly int MaxCount;


    public const int __ID__ = -1824387441;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "containerId:" + ContainerId + ","
        + "itemId:" + ItemId + ","
        + "weight:" + Weight + ","
        + "minCount:" + MinCount + ","
        + "maxCount:" + MaxCount + ","
        + "}";
    }
}
}

