
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 小纸条记录
/// </summary>

public sealed partial class Note : Luban.BeanBase
{
    public Note(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Title = (string)_obj.GetValue("title");
        Content = (string)_obj.GetValue("content");
    }

    public static Note DeserializeNote(JToken _buf)
    {
        return new cfg.Note(_buf);
    }

    /// <summary>
    /// 纸条ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly string Title;
    /// <summary>
    /// 正文(支持<br/>换行)
    /// </summary>
    public readonly string Content;


    public const int __ID__ = -230655140;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "title:" + Title + ","
        + "content:" + Content + ","
        + "}";
    }
}
}

