
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// NPC记录
/// </summary>

public sealed partial class Npc : Luban.BeanBase
{
    public Npc(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Role = (string)_obj.GetValue("role");
        MoveSpeed = (float)_obj.GetValue("moveSpeed");
        PatrolPath = (string)_obj.GetValue("patrolPath");
        DialogueId = (int)_obj.GetValue("dialogueId");
    }

    public static Npc DeserializeNpc(JToken _buf)
    {
        return new cfg.Npc(_buf);
    }

    /// <summary>
    /// NPC ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 身份/职业
    /// </summary>
    public readonly string Role;
    /// <summary>
    /// 移动速度(0=站桩)
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 巡逻路径(x,z|x,z 空=不巡逻)
    /// </summary>
    public readonly string PatrolPath;
    /// <summary>
    /// 对话ID(预留,0=无)
    /// </summary>
    public readonly int DialogueId;


    public const int __ID__ = 685296183;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "role:" + Role + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "patrolPath:" + PatrolPath + ","
        + "dialogueId:" + DialogueId + ","
        + "}";
    }
}
}

