
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 订单配置
/// </summary>

public sealed partial class Order : Luban.BeanBase
{
    public Order(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        { var __json0 = _obj.GetValue("requiredItems"); RequiredItems = new System.Collections.Generic.List<cfg.ItemExchange>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { cfg.ItemExchange __v0;  __v0 = global::GameConfig.cfg.ItemExchange.DeserializeItemExchange(__e0);  RequiredItems.Add(__v0); }   }
        RewardGold = (int)_obj.GetValue("rewardGold");
        { var __json0 = _obj.GetValue("rewardItems"); RewardItems = new System.Collections.Generic.List<cfg.ItemExchange>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { cfg.ItemExchange __v0;  __v0 = global::GameConfig.cfg.ItemExchange.DeserializeItemExchange(__e0);  RewardItems.Add(__v0); }   }
        RewardExp = (int)_obj.GetValue("rewardExp");
        TimeLimit = (float)_obj.GetValue("timeLimit");
        Weight = (int)_obj.GetValue("weight");
        MinPlayerLevel = (int)_obj.GetValue("minPlayerLevel");
    }

    public static Order DeserializeOrder(JToken _buf)
    {
        return new cfg.Order(_buf);
    }

    /// <summary>
    /// 订单ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 需求物品
    /// </summary>
    public readonly System.Collections.Generic.List<cfg.ItemExchange> RequiredItems;
    /// <summary>
    /// 奖励金币
    /// </summary>
    public readonly int RewardGold;
    /// <summary>
    /// 奖励物品
    /// </summary>
    public readonly System.Collections.Generic.List<cfg.ItemExchange> RewardItems;
    /// <summary>
    /// 奖励经验
    /// </summary>
    public readonly int RewardExp;
    /// <summary>
    /// 时限
    /// </summary>
    public readonly float TimeLimit;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 最低等级
    /// </summary>
    public readonly int MinPlayerLevel;


    public const int __ID__ = 1440622884;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in RequiredItems) { _e?.ResolveRef(tables); }
        foreach (var _e in RewardItems) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "requiredItems:" + Luban.StringUtil.CollectionToString(RequiredItems) + ","
        + "rewardGold:" + RewardGold + ","
        + "rewardItems:" + Luban.StringUtil.CollectionToString(RewardItems) + ","
        + "rewardExp:" + RewardExp + ","
        + "timeLimit:" + TimeLimit + ","
        + "weight:" + Weight + ","
        + "minPlayerLevel:" + MinPlayerLevel + ","
        + "}";
    }
}
}

