
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 拾取物配置
/// </summary>

public sealed partial class Pickup : Luban.BeanBase
{
    public Pickup(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        ColliderRadius = (float)_obj.GetValue("colliderRadius");
        VisualScale = (float)_obj.GetValue("visualScale");
        SortingOrder = (int)_obj.GetValue("sortingOrder");
    }

    public static Pickup DeserializePickup(JToken _buf)
    {
        return new cfg.Pickup(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 拾取物碰撞体半径
    /// </summary>
    public readonly float ColliderRadius;
    /// <summary>
    /// 拾取物视觉缩放
    /// </summary>
    public readonly float VisualScale;
    /// <summary>
    /// 拾取物渲染排序
    /// </summary>
    public readonly int SortingOrder;


    public const int __ID__ = 2100000004;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "colliderradius:" + ColliderRadius + ","
        + "visualscale:" + VisualScale + ","
        + "sortingorder:" + SortingOrder + ""
        + "}";
    }
}
}
