
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 玩家等级经验表
/// </summary>

public sealed partial class PlayerLevel : Luban.BeanBase
{
    public PlayerLevel(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Level = (int)_obj.GetValue("level");
        ExpToNext = (int)_obj.GetValue("expToNext");
    }

    public static PlayerLevel DeserializePlayerLevel(JToken _buf)
    {
        return new cfg.PlayerLevel(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 升到下一级所需经验
    /// </summary>
    public readonly int ExpToNext;


    public const int __ID__ = -1704452487;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "expToNext:" + ExpToNext + ","
        + "}";
    }
}
}

