
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 玩家属性
/// </summary>

public sealed partial class Player : Luban.BeanBase
{
    public Player(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        MaxHp = (int)_obj.GetValue("maxHp");
        MoveSpeed = (float)_obj.GetValue("moveSpeed");
        RotationSpeed = (float)_obj.GetValue("rotationSpeed");
        ColliderRadius = (float)_obj.GetValue("colliderRadius");
        Prefab = (string)_obj.GetValue("prefab");
    }

    public static Player DeserializePlayer(JToken _buf)
    {
        return new cfg.Player(_buf);
    }

    /// <summary>
    /// 配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 最大血量
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 旋转速度
    /// </summary>
    public readonly float RotationSpeed;
    /// <summary>
    /// 碰撞体半径
    /// </summary>
    public readonly float ColliderRadius;
    /// <summary>
    /// 预制体
    /// </summary>
    public readonly string Prefab;


    public const int __ID__ = 1732654027;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "maxHp:" + MaxHp + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "rotationSpeed:" + RotationSpeed + ","
        + "colliderRadius:" + ColliderRadius + ","
        + "prefab:" + Prefab + ","
        + "}";
    }
}
}

