
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 玩家属性
/// </summary>

public sealed partial class Player : Luban.BeanBase
{
    public Player(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        MaxHp = (int)_obj.GetValue("maxHp");
        MaxStamina = (int)_obj.GetValue("maxStamina");
        StaminaRecoveryRate = (float)_obj.GetValue("staminaRecoveryRate");
        DodgeStaminaCost = (int)_obj.GetValue("dodgeStaminaCost");
        MoveSpeed = (float)_obj.GetValue("moveSpeed");
        DodgeSpeed = (float)_obj.GetValue("dodgeSpeed");
        DodgeDuration = (float)_obj.GetValue("dodgeDuration");
        RotationSpeed = (float)_obj.GetValue("rotationSpeed");
        ColliderRadius = (float)_obj.GetValue("colliderRadius");
        Prefab = (string)_obj.GetValue("prefab");
        WeaponSwitchCooldown = (float)_obj.GetValue("weaponSwitchCooldown");
        IdleAnim = (string)_obj.GetValue("idleAnim");
        MoveAnim = (string)_obj.GetValue("moveAnim");
        DodgeAnim = (string)_obj.GetValue("dodgeAnim");
        ReloadAnim = (string)_obj.GetValue("reloadAnim");
        DeadAnim = (string)_obj.GetValue("deadAnim");
    }

    public static Player DeserializePlayer(JToken _buf)
    {
        return new cfg.Player(_buf);
    }

    /// <summary>
    /// 玩家ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 最大血量
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 最大体力
    /// </summary>
    public readonly int MaxStamina;
    /// <summary>
    /// 体力恢复速率
    /// </summary>
    public readonly float StaminaRecoveryRate;
    /// <summary>
    /// 闪避消耗体力
    /// </summary>
    public readonly int DodgeStaminaCost;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 闪避速度
    /// </summary>
    public readonly float DodgeSpeed;
    /// <summary>
    /// 闪避持续时间
    /// </summary>
    public readonly float DodgeDuration;
    /// <summary>
    /// 旋转速度
    /// </summary>
    public readonly float RotationSpeed;
    /// <summary>
    /// 碰撞体半径
    /// </summary>
    public readonly float ColliderRadius;
    /// <summary>
    /// 预制体
    /// </summary>
    public readonly string Prefab;
    /// <summary>
    /// 武器切换冷却
    /// </summary>
    public readonly float WeaponSwitchCooldown;
    /// <summary>
    /// 待机动画名
    /// </summary>
    public readonly string IdleAnim;
    /// <summary>
    /// 移动动画名
    /// </summary>
    public readonly string MoveAnim;
    /// <summary>
    /// 闪避动画名
    /// </summary>
    public readonly string DodgeAnim;
    /// <summary>
    /// 换弹动画名
    /// </summary>
    public readonly string ReloadAnim;
    /// <summary>
    /// 死亡动画名
    /// </summary>
    public readonly string DeadAnim;


    public const int __ID__ = 1732654027;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "maxhp:" + MaxHp + ","
        + "maxstamina:" + MaxStamina + ","
        + "staminarecoveryrate:" + StaminaRecoveryRate + ","
        + "dodgestaminacost:" + DodgeStaminaCost + ","
        + "movespeed:" + MoveSpeed + ","
        + "dodgespeed:" + DodgeSpeed + ","
        + "dodgeduration:" + DodgeDuration + ","
        + "rotationspeed:" + RotationSpeed + ","
        + "colliderradius:" + ColliderRadius + ","
        + "prefab:" + Prefab + ","
        + "weaponswitchcooldown:" + WeaponSwitchCooldown + ","
        + "idleanim:" + IdleAnim + ","
        + "moveanim:" + MoveAnim + ","
        + "dodgeanim:" + DodgeAnim + ","
        + "reloadanim:" + ReloadAnim + ","
        + "deadanim:" + DeadAnim + ""
        + "}";
    }
}
}
