
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 传送门配置
/// </summary>

public sealed partial class Portal : Luban.BeanBase
{
    public Portal(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        PortalType = (string)_obj.GetValue("portalType");
        TargetLevelId = (int)_obj.GetValue("targetLevelId");
        TargetSceneName = (string)_obj.GetValue("targetSceneName");
        SpawnCondition = (string)_obj.GetValue("spawnCondition");
        ConditionParam = (string)_obj.GetValue("conditionParam");
        KeepPlayerState = (bool)_obj.GetValue("keepPlayerState");
        PromptText = (string)_obj.GetValue("promptText");
        TransitionType = (string)_obj.GetValue("transitionType");
        TransitionDuration = (float)_obj.GetValue("transitionDuration");
    }

    public static Portal DeserializePortal(JToken _buf)
    {
        return new cfg.Portal(_buf);
    }

    /// <summary>
    /// 传送门ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 传送门类型
    /// </summary>
    public readonly string PortalType;
    /// <summary>
    /// 目标关卡ID
    /// </summary>
    public readonly int TargetLevelId;
    /// <summary>
    /// 目标场景名
    /// </summary>
    public readonly string TargetSceneName;
    /// <summary>
    /// 出现条件
    /// </summary>
    public readonly string SpawnCondition;
    /// <summary>
    /// 条件参数
    /// </summary>
    public readonly string ConditionParam;
    /// <summary>
    /// 保留玩家状态
    /// </summary>
    public readonly bool KeepPlayerState;
    /// <summary>
    /// 提示文本
    /// </summary>
    public readonly string PromptText;
    /// <summary>
    /// 转场类型
    /// </summary>
    public readonly string TransitionType;
    /// <summary>
    /// 转场时长
    /// </summary>
    public readonly float TransitionDuration;


    public const int __ID__ = 1735926102;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "portalType:" + PortalType + ","
        + "targetLevelId:" + TargetLevelId + ","
        + "targetSceneName:" + TargetSceneName + ","
        + "spawnCondition:" + SpawnCondition + ","
        + "conditionParam:" + ConditionParam + ","
        + "keepPlayerState:" + KeepPlayerState + ","
        + "promptText:" + PromptText + ","
        + "transitionType:" + TransitionType + ","
        + "transitionDuration:" + TransitionDuration + ","
        + "}";
    }
}
}

