
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 生产配方
/// </summary>

public sealed partial class Production : Luban.BeanBase
{
    public Production(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Desc = (string)_obj.GetValue("desc");
        BuildingId = (int)_obj.GetValue("buildingId");
        LevelRequired = (int)_obj.GetValue("levelRequired");
        { var __json0 = _obj.GetValue("inputItems"); InputItems = new System.Collections.Generic.List<cfg.ItemExchange>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { cfg.ItemExchange __v0;  __v0 = global::GameConfig.cfg.ItemExchange.DeserializeItemExchange(__e0);  InputItems.Add(__v0); }   }
        OutputItemId = (int)_obj.GetValue("outputItemId");
        OutputCount = (int)_obj.GetValue("outputCount");
        ProductionTime = (float)_obj.GetValue("productionTime");
        Icon = (string)_obj.GetValue("icon");
    }

    public static Production DeserializeProduction(JToken _buf)
    {
        return new cfg.Production(_buf);
    }

    /// <summary>
    /// 配方ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 建筑ID
    /// </summary>
    public readonly int BuildingId;
    /// <summary>
    /// 等级要求
    /// </summary>
    public readonly int LevelRequired;
    /// <summary>
    /// 输入材料
    /// </summary>
    public readonly System.Collections.Generic.List<cfg.ItemExchange> InputItems;
    /// <summary>
    /// 产出物品
    /// </summary>
    public readonly int OutputItemId;
    /// <summary>
    /// 产出数量
    /// </summary>
    public readonly int OutputCount;
    /// <summary>
    /// 生产耗时
    /// </summary>
    public readonly float ProductionTime;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;


    public const int __ID__ = 433718435;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in InputItems) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "buildingId:" + BuildingId + ","
        + "levelRequired:" + LevelRequired + ","
        + "inputItems:" + Luban.StringUtil.CollectionToString(InputItems) + ","
        + "outputItemId:" + OutputItemId + ","
        + "outputCount:" + OutputCount + ","
        + "productionTime:" + ProductionTime + ","
        + "icon:" + Icon + ","
        + "}";
    }
}
}

