
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 任务目标
/// </summary>

public sealed partial class QuestObjective : Luban.BeanBase
{
    public QuestObjective(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        QuestId = (int)_obj.GetValue("questId");
        Type = (string)_obj.GetValue("type");
        TargetId = (string)_obj.GetValue("targetId");
        Count = (int)_obj.GetValue("count");
        Desc = (string)_obj.GetValue("desc");
    }

    public static QuestObjective DeserializeQuestObjective(JToken _buf)
    {
        return new cfg.QuestObjective(_buf);
    }

    /// <summary>
    /// 目标ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属任务
    /// </summary>
    public readonly int QuestId;
    /// <summary>
    /// 类型(kill/collect/extract/flag)
    /// </summary>
    public readonly string Type;
    /// <summary>
    /// 目标ID/标志键
    /// </summary>
    public readonly string TargetId;
    /// <summary>
    /// 需求数(extract恒1)
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 目标一行描述
    /// </summary>
    public readonly string Desc;


    public const int __ID__ = 1141353825;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "questId:" + QuestId + ","
        + "type:" + Type + ","
        + "targetId:" + TargetId + ","
        + "count:" + Count + ","
        + "desc:" + Desc + ","
        + "}";
    }
}
}

