
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 任务定义
/// </summary>

public sealed partial class Quest : Luban.BeanBase
{
    public Quest(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Desc = (string)_obj.GetValue("desc");
        GiverNpc = (int)_obj.GetValue("giverNpc");
        Prereq = (string)_obj.GetValue("prereq");
        Rewards = (string)_obj.GetValue("rewards");
        NextQuest = (int)_obj.GetValue("nextQuest");
    }

    public static Quest DeserializeQuest(JToken _buf)
    {
        return new cfg.Quest(_buf);
    }

    /// <summary>
    /// 任务ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 发布NPC(0=任务板)
    /// </summary>
    public readonly int GiverNpc;
    /// <summary>
    /// 接取条件表达式(空=无)
    /// </summary>
    public readonly string Prereq;
    /// <summary>
    /// 奖励(gold:200|exp:50|item:3001:2)
    /// </summary>
    public readonly string Rewards;
    /// <summary>
    /// 后继任务(0=无)
    /// </summary>
    public readonly int NextQuest;


    public const int __ID__ = 1442560696;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "giverNpc:" + GiverNpc + ","
        + "prereq:" + Prereq + ","
        + "rewards:" + Rewards + ","
        + "nextQuest:" + NextQuest + ","
        + "}";
    }
}
}

