
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 经营时间配置
/// </summary>

public sealed partial class SimTimeConfig : Luban.BeanBase
{
    public SimTimeConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        BaseSpeed = (float)_obj.GetValue("baseSpeed");
        FastSpeed = (float)_obj.GetValue("fastSpeed");
        MaxSpeed = (float)_obj.GetValue("maxSpeed");
        OrderRefreshInterval = (float)_obj.GetValue("orderRefreshInterval");
        MaxOrderCount = (int)_obj.GetValue("maxOrderCount");
    }

    public static SimTimeConfig DeserializeSimTimeConfig(JToken _buf)
    {
        return new cfg.SimTimeConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 基础速度
    /// </summary>
    public readonly float BaseSpeed;
    /// <summary>
    /// 加速速度
    /// </summary>
    public readonly float FastSpeed;
    /// <summary>
    /// 最大速度
    /// </summary>
    public readonly float MaxSpeed;
    /// <summary>
    /// 订单刷新间隔
    /// </summary>
    public readonly float OrderRefreshInterval;
    /// <summary>
    /// 最大订单数
    /// </summary>
    public readonly int MaxOrderCount;


    public const int __ID__ = 992860284;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "baseSpeed:" + BaseSpeed + ","
        + "fastSpeed:" + FastSpeed + ","
        + "maxSpeed:" + MaxSpeed + ","
        + "orderRefreshInterval:" + OrderRefreshInterval + ","
        + "maxOrderCount:" + MaxOrderCount + ","
        + "}";
    }
}
}

