
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 技能节点
/// </summary>

public sealed partial class Skill : Luban.BeanBase
{
    public Skill(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        NameKey = (string)_obj.GetValue("nameKey");
        DescKey = (string)_obj.GetValue("descKey");
        Branch = (int)_obj.GetValue("branch");
        MaxLevel = (int)_obj.GetValue("maxLevel");
        EffectType = (cfg.ESkillEffect)(int)_obj.GetValue("effectType");
        EffectValue = (float)_obj.GetValue("effectValue");
        { var __json0 = _obj.GetValue("costItems"); CostItems = new System.Collections.Generic.List<cfg.ItemExchange>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { cfg.ItemExchange __v0;  __v0 = global::GameConfig.cfg.ItemExchange.DeserializeItemExchange(__e0);  CostItems.Add(__v0); }   }
        CostGold = (long)_obj.GetValue("costGold");
        PrereqSkillId = (int)_obj.GetValue("prereqSkillId");
        Row = (int)_obj.GetValue("row");
        Col = (int)_obj.GetValue("col");
        Icon = (string)_obj.GetValue("icon");
    }

    public static Skill DeserializeSkill(JToken _buf)
    {
        return new cfg.Skill(_buf);
    }

    /// <summary>
    /// 技能ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称词条键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 描述词条键
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 分支(1战斗2生存3经营)
    /// </summary>
    public readonly int Branch;
    /// <summary>
    /// 最大等级
    /// </summary>
    public readonly int MaxLevel;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly cfg.ESkillEffect EffectType;
    /// <summary>
    /// 每级效果值
    /// </summary>
    public readonly float EffectValue;
    /// <summary>
    /// 每级材料消耗
    /// </summary>
    public readonly System.Collections.Generic.List<cfg.ItemExchange> CostItems;
    /// <summary>
    /// 每级金币消耗
    /// </summary>
    public readonly long CostGold;
    /// <summary>
    /// 前置技能(需满级,0=无)
    /// </summary>
    public readonly int PrereqSkillId;
    /// <summary>
    /// 树UI行
    /// </summary>
    public readonly int Row;
    /// <summary>
    /// 树UI列
    /// </summary>
    public readonly int Col;
    /// <summary>
    /// 图标资源地址
    /// </summary>
    public readonly string Icon;


    public const int __ID__ = 1444113447;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in CostItems) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "branch:" + Branch + ","
        + "maxLevel:" + MaxLevel + ","
        + "effectType:" + EffectType + ","
        + "effectValue:" + EffectValue + ","
        + "costItems:" + Luban.StringUtil.CollectionToString(CostItems) + ","
        + "costGold:" + CostGold + ","
        + "prereqSkillId:" + PrereqSkillId + ","
        + "row:" + Row + ","
        + "col:" + Col + ","
        + "icon:" + Icon + ","
        + "}";
    }
}
}

