
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

public partial class TbAudio
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Audio> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Audio> _dataList;
    
    public TbAudio(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Audio>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Audio>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Audio _v;
            _v = global::GameConfig.cfg.Audio.DeserializeAudio(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Audio> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Audio> DataList => _dataList;

    public cfg.Audio GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Audio Get(int key) => _dataMap[key];
    public cfg.Audio this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

