
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 弹道全局配置表
/// </summary>
public partial class TbBallistic
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Ballistic> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Ballistic> _dataList;
    
    public TbBallistic(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Ballistic>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Ballistic>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Ballistic _v;
            _v = global::GameConfig.cfg.Ballistic.DeserializeBallistic(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Ballistic> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Ballistic> DataList => _dataList;

    public cfg.Ballistic GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Ballistic Get(int key) => _dataMap[key];
    public cfg.Ballistic this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}
