
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// Buff表
/// </summary>
public partial class TbBuff
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Buff> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Buff> _dataList;
    
    public TbBuff(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Buff>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Buff>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Buff _v;
            _v = global::GameConfig.cfg.Buff.DeserializeBuff(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Buff> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Buff> DataList => _dataList;

    public cfg.Buff GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Buff Get(int key) => _dataMap[key];
    public cfg.Buff this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

