
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 相机配置表
/// </summary>
public partial class TbCamera
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Camera> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Camera> _dataList;
    
    public TbCamera(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Camera>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Camera>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Camera _v;
            _v = global::GameConfig.cfg.Camera.DeserializeCamera(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Camera> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Camera> DataList => _dataList;

    public cfg.Camera GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Camera Get(int key) => _dataMap[key];
    public cfg.Camera this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}
