
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 队友本地台词表
/// </summary>
public partial class TbCompanionBark
{
    private readonly System.Collections.Generic.List<cfg.CompanionBark> _dataList;



    public TbCompanionBark(JArray _buf)
    {
        _dataList = new System.Collections.Generic.List<cfg.CompanionBark>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.CompanionBark _v;
            _v = global::GameConfig.cfg.CompanionBark.DeserializeCompanionBark(_ele);
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<cfg.CompanionBark> DataList => _dataList;



    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

