
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 好感获取规则表
/// </summary>
public partial class TbCompanionAffinityGain
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.CompanionAffinityGain> _dataMap;
    private readonly System.Collections.Generic.List<cfg.CompanionAffinityGain> _dataList;
    
    public TbCompanionAffinityGain(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.CompanionAffinityGain>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.CompanionAffinityGain>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.CompanionAffinityGain _v;
            _v = global::GameConfig.cfg.CompanionAffinityGain.DeserializeCompanionAffinityGain(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Source, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.CompanionAffinityGain> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.CompanionAffinityGain> DataList => _dataList;

    public cfg.CompanionAffinityGain GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.CompanionAffinityGain Get(string key) => _dataMap[key];
    public cfg.CompanionAffinityGain this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

