
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 队友记忆规则表
/// </summary>
public partial class TbCompanionMemoryRule
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.CompanionMemoryRule> _dataMap;
    private readonly System.Collections.Generic.List<cfg.CompanionMemoryRule> _dataList;
    
    public TbCompanionMemoryRule(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.CompanionMemoryRule>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.CompanionMemoryRule>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.CompanionMemoryRule _v;
            _v = global::GameConfig.cfg.CompanionMemoryRule.DeserializeCompanionMemoryRule(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.CompanionMemoryRule> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.CompanionMemoryRule> DataList => _dataList;

    public cfg.CompanionMemoryRule GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.CompanionMemoryRule Get(int key) => _dataMap[key];
    public cfg.CompanionMemoryRule this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

