
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 队友人设卡
/// </summary>
public partial class TbCompanion
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Companion> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Companion> _dataList;
    
    public TbCompanion(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Companion>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Companion>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Companion _v;
            _v = global::GameConfig.cfg.Companion.DeserializeCompanion(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Companion> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Companion> DataList => _dataList;

    public cfg.Companion GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Companion Get(int key) => _dataMap[key];
    public cfg.Companion this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

