
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 队友分档人格提示表
/// </summary>
public partial class TbCompanionPersona
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.CompanionPersona> _dataMap;
    private readonly System.Collections.Generic.List<cfg.CompanionPersona> _dataList;
    
    public TbCompanionPersona(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.CompanionPersona>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.CompanionPersona>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.CompanionPersona _v;
            _v = global::GameConfig.cfg.CompanionPersona.DeserializeCompanionPersona(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.CompanionPersona> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.CompanionPersona> DataList => _dataList;

    public cfg.CompanionPersona GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.CompanionPersona Get(int key) => _dataMap[key];
    public cfg.CompanionPersona this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

