
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 好感档位表
/// </summary>
public partial class TbCompanionAffinityTier
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.CompanionAffinityTier> _dataMap;
    private readonly System.Collections.Generic.List<cfg.CompanionAffinityTier> _dataList;
    
    public TbCompanionAffinityTier(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.CompanionAffinityTier>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.CompanionAffinityTier>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.CompanionAffinityTier _v;
            _v = global::GameConfig.cfg.CompanionAffinityTier.DeserializeCompanionAffinityTier(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Tier, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.CompanionAffinityTier> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.CompanionAffinityTier> DataList => _dataList;

    public cfg.CompanionAffinityTier GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.CompanionAffinityTier Get(int key) => _dataMap[key];
    public cfg.CompanionAffinityTier this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

