
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 对话头表
/// </summary>
public partial class TbDialogue
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Dialogue> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Dialogue> _dataList;
    
    public TbDialogue(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Dialogue>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Dialogue>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Dialogue _v;
            _v = global::GameConfig.cfg.Dialogue.DeserializeDialogue(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Dialogue> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Dialogue> DataList => _dataList;

    public cfg.Dialogue GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Dialogue Get(int key) => _dataMap[key];
    public cfg.Dialogue this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

