
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 敌人属性表
/// </summary>
public partial class TbEnemy
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Enemy> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Enemy> _dataList;
    
    public TbEnemy(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Enemy>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Enemy>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Enemy _v;
            _v = global::GameConfig.cfg.Enemy.DeserializeEnemy(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Enemy> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Enemy> DataList => _dataList;

    public cfg.Enemy GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Enemy Get(int key) => _dataMap[key];
    public cfg.Enemy this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

