
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 背包容量表
/// </summary>
public partial class TbInventoryConfig
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.InventoryConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.InventoryConfig> _dataList;
    
    public TbInventoryConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.InventoryConfig>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.InventoryConfig>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.InventoryConfig _v;
            _v = global::GameConfig.cfg.InventoryConfig.DeserializeInventoryConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.InventoryConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.InventoryConfig> DataList => _dataList;

    public cfg.InventoryConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.InventoryConfig Get(int key) => _dataMap[key];
    public cfg.InventoryConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

