
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 容器掉落表
/// </summary>
public partial class TbLootContainer
{
    private readonly System.Collections.Generic.List<cfg.LootContainer> _dataList;

    private System.Collections.Generic.Dictionary<int, cfg.LootContainer> _dataMap_id;


    public TbLootContainer(JArray _buf)
    {
        _dataList = new System.Collections.Generic.List<cfg.LootContainer>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.LootContainer _v;
            _v = global::GameConfig.cfg.LootContainer.DeserializeLootContainer(_ele);
            _dataList.Add(_v);
        }
            _dataMap_id = new System.Collections.Generic.Dictionary<int, cfg.LootContainer>(_buf.Count);
            foreach(var _v in _dataList)
            {
                _dataMap_id.Add(_v.Id, _v);
            }
    }

    public System.Collections.Generic.IReadOnlyList<cfg.LootContainer> DataList => _dataList;


    public cfg.LootContainer GetById(int key) => _dataMap_id.TryGetValue(key, out cfg.LootContainer __v) ? __v : default;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

