
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 小纸条表
/// </summary>
public partial class TbNote
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Note> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Note> _dataList;
    
    public TbNote(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Note>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Note>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Note _v;
            _v = global::GameConfig.cfg.Note.DeserializeNote(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Note> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Note> DataList => _dataList;

    public cfg.Note GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Note Get(int key) => _dataMap[key];
    public cfg.Note this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

