
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 拾取物配置表
/// </summary>
public partial class TbPickup
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Pickup> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Pickup> _dataList;
    
    public TbPickup(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Pickup>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Pickup>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Pickup _v;
            _v = global::GameConfig.cfg.Pickup.DeserializePickup(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Pickup> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Pickup> DataList => _dataList;

    public cfg.Pickup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Pickup Get(int key) => _dataMap[key];
    public cfg.Pickup this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}
