
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 玩家属性表
/// </summary>
public partial class TbPlayer
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Player> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Player> _dataList;
    
    public TbPlayer(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Player>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Player>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Player _v;
            _v = global::GameConfig.cfg.Player.DeserializePlayer(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Player> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Player> DataList => _dataList;

    public cfg.Player GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Player Get(int key) => _dataMap[key];
    public cfg.Player this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

