
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 玩家等级经验表
/// </summary>
public partial class TbPlayerLevel
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.PlayerLevel> _dataMap;
    private readonly System.Collections.Generic.List<cfg.PlayerLevel> _dataList;
    
    public TbPlayerLevel(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.PlayerLevel>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.PlayerLevel>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.PlayerLevel _v;
            _v = global::GameConfig.cfg.PlayerLevel.DeserializePlayerLevel(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.PlayerLevel> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.PlayerLevel> DataList => _dataList;

    public cfg.PlayerLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.PlayerLevel Get(int key) => _dataMap[key];
    public cfg.PlayerLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

