
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 传送门表
/// </summary>
public partial class TbPortal
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Portal> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Portal> _dataList;
    
    public TbPortal(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Portal>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Portal>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Portal _v;
            _v = global::GameConfig.cfg.Portal.DeserializePortal(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Portal> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Portal> DataList => _dataList;

    public cfg.Portal GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Portal Get(int key) => _dataMap[key];
    public cfg.Portal this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

