
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 生产配方表
/// </summary>
public partial class TbProduction
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Production> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Production> _dataList;
    
    public TbProduction(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Production>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Production>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Production _v;
            _v = global::GameConfig.cfg.Production.DeserializeProduction(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Production> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Production> DataList => _dataList;

    public cfg.Production GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Production Get(int key) => _dataMap[key];
    public cfg.Production this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

