
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 任务目标表
/// </summary>
public partial class TbQuestObjective
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.QuestObjective> _dataMap;
    private readonly System.Collections.Generic.List<cfg.QuestObjective> _dataList;
    
    public TbQuestObjective(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.QuestObjective>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.QuestObjective>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.QuestObjective _v;
            _v = global::GameConfig.cfg.QuestObjective.DeserializeQuestObjective(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.QuestObjective> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.QuestObjective> DataList => _dataList;

    public cfg.QuestObjective GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.QuestObjective Get(int key) => _dataMap[key];
    public cfg.QuestObjective this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

