
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 任务表
/// </summary>
public partial class TbQuest
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Quest> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Quest> _dataList;
    
    public TbQuest(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Quest>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Quest>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Quest _v;
            _v = global::GameConfig.cfg.Quest.DeserializeQuest(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Quest> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Quest> DataList => _dataList;

    public cfg.Quest GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Quest Get(int key) => _dataMap[key];
    public cfg.Quest this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

