
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 经营时间配置
/// </summary>
public partial class TbSimTimeConfig
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.SimTimeConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.SimTimeConfig> _dataList;
    
    public TbSimTimeConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.SimTimeConfig>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.SimTimeConfig>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.SimTimeConfig _v;
            _v = global::GameConfig.cfg.SimTimeConfig.DeserializeSimTimeConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.SimTimeConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.SimTimeConfig> DataList => _dataList;

    public cfg.SimTimeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.SimTimeConfig Get(int key) => _dataMap[key];
    public cfg.SimTimeConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

