
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 技能树表
/// </summary>
public partial class TbSkill
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Skill> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Skill> _dataList;
    
    public TbSkill(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Skill>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Skill>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Skill _v;
            _v = global::GameConfig.cfg.Skill.DeserializeSkill(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Skill> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Skill> DataList => _dataList;

    public cfg.Skill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Skill Get(int key) => _dataMap[key];
    public cfg.Skill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

