
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// UI全局配置表
/// </summary>
public partial class TbUiConfig
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.UiConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.UiConfig> _dataList;
    
    public TbUiConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.UiConfig>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.UiConfig>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.UiConfig _v;
            _v = global::GameConfig.cfg.UiConfig.DeserializeUiConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.UiConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.UiConfig> DataList => _dataList;

    public cfg.UiConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.UiConfig Get(int key) => _dataMap[key];
    public cfg.UiConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}
