
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 内容解锁表
/// </summary>
public partial class TbUnlock
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Unlock> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Unlock> _dataList;
    
    public TbUnlock(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Unlock>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Unlock>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Unlock _v;
            _v = global::GameConfig.cfg.Unlock.DeserializeUnlock(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Unlock> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Unlock> DataList => _dataList;

    public cfg.Unlock GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Unlock Get(int key) => _dataMap[key];
    public cfg.Unlock this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

