
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.cfg
{

/// <summary>
/// 武器表
/// </summary>
public partial class TbWeapon
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.Weapon> _dataMap;
    private readonly System.Collections.Generic.List<cfg.Weapon> _dataList;
    
    public TbWeapon(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.Weapon>(_buf.Count);
        _dataList = new System.Collections.Generic.List<cfg.Weapon>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            cfg.Weapon _v;
            _v = global::GameConfig.cfg.Weapon.DeserializeWeapon(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.Weapon> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.Weapon> DataList => _dataList;

    public cfg.Weapon GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.Weapon Get(int key) => _dataMap[key];
    public cfg.Weapon this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

