
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// UI全局配置
/// </summary>

public sealed partial class UiConfig : Luban.BeanBase
{
    public UiConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        DamageNumberPoolSize = (int)_obj.GetValue("damageNumberPoolSize");
        DamageNumberFadeDuration = (float)_obj.GetValue("damageNumberFadeDuration");
        DamageNumberMoveOffset = (float)_obj.GetValue("damageNumberMoveOffset");
        DamageNumberNormalColor = global::GameConfig.cfg.Color.DeserializeColor(_obj.GetValue("damageNumberNormalColor"));
        DamageNumberCriticalColor = global::GameConfig.cfg.Color.DeserializeColor(_obj.GetValue("damageNumberCriticalColor"));
        DamageNumberNormalFontSize = (int)_obj.GetValue("damageNumberNormalFontSize");
        DamageNumberCriticalFontSize = (int)_obj.GetValue("damageNumberCriticalFontSize");
        HitMarkerPoolSize = (int)_obj.GetValue("hitMarkerPoolSize");
        HitMarkerDuration = (float)_obj.GetValue("hitMarkerDuration");
        HitMarkerSize = (float)_obj.GetValue("hitMarkerSize");
        HitMarkerNormalColor = global::GameConfig.cfg.Color.DeserializeColor(_obj.GetValue("hitMarkerNormalColor"));
        HitMarkerCriticalColor = global::GameConfig.cfg.Color.DeserializeColor(_obj.GetValue("hitMarkerCriticalColor"));
        IndicatorFadeSpeed = (float)_obj.GetValue("indicatorFadeSpeed");
        IndicatorColor = global::GameConfig.cfg.Color.DeserializeColor(_obj.GetValue("indicatorColor"));
        LoadingTextFormat = (string)_obj.GetValue("loadingTextFormat");
    }

    public static UiConfig DeserializeUiConfig(JToken _buf)
    {
        return new cfg.UiConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 伤害数字对象池大小
    /// </summary>
    public readonly int DamageNumberPoolSize;
    /// <summary>
    /// 伤害数字渐隐时间
    /// </summary>
    public readonly float DamageNumberFadeDuration;
    /// <summary>
    /// 伤害数字上浮偏移
    /// </summary>
    public readonly float DamageNumberMoveOffset;
    /// <summary>
    /// 普通伤害数字颜色
    /// </summary>
    public readonly cfg.Color DamageNumberNormalColor;
    /// <summary>
    /// 暴击伤害数字颜色
    /// </summary>
    public readonly cfg.Color DamageNumberCriticalColor;
    /// <summary>
    /// 普通伤害数字字体大小
    /// </summary>
    public readonly int DamageNumberNormalFontSize;
    /// <summary>
    /// 暴击伤害数字字体大小
    /// </summary>
    public readonly int DamageNumberCriticalFontSize;
    /// <summary>
    /// 命中标记对象池大小
    /// </summary>
    public readonly int HitMarkerPoolSize;
    /// <summary>
    /// 命中标记显示时间
    /// </summary>
    public readonly float HitMarkerDuration;
    /// <summary>
    /// 命中标记大小
    /// </summary>
    public readonly float HitMarkerSize;
    /// <summary>
    /// 普通命中标记颜色
    /// </summary>
    public readonly cfg.Color HitMarkerNormalColor;
    /// <summary>
    /// 暴击命中标记颜色
    /// </summary>
    public readonly cfg.Color HitMarkerCriticalColor;
    /// <summary>
    /// 受击指示器淡出速度
    /// </summary>
    public readonly float IndicatorFadeSpeed;
    /// <summary>
    /// 受击指示器颜色
    /// </summary>
    public readonly cfg.Color IndicatorColor;
    /// <summary>
    /// 加载进度文本格式
    /// </summary>
    public readonly string LoadingTextFormat;


    public const int __ID__ = 2100000003;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        DamageNumberNormalColor?.ResolveRef(tables);
        DamageNumberCriticalColor?.ResolveRef(tables);
        HitMarkerNormalColor?.ResolveRef(tables);
        HitMarkerCriticalColor?.ResolveRef(tables);
        IndicatorColor?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "damagenumberpoolsize:" + DamageNumberPoolSize + ","
        + "damagenumberfadeduration:" + DamageNumberFadeDuration + ","
        + "damagenumbermoveoffset:" + DamageNumberMoveOffset + ","
        + "damagenumbernormalcolor:" + DamageNumberNormalColor + ","
        + "damagenumbercriticalcolor:" + DamageNumberCriticalColor + ","
        + "damagenumbernormalfontsize:" + DamageNumberNormalFontSize + ","
        + "damagenumbercriticalfontsize:" + DamageNumberCriticalFontSize + ","
        + "hitmarkerpoolsize:" + HitMarkerPoolSize + ","
        + "hitmarkerduration:" + HitMarkerDuration + ","
        + "hitmarkersize:" + HitMarkerSize + ","
        + "hitmarkernormalcolor:" + HitMarkerNormalColor + ","
        + "hitmarkercriticalcolor:" + HitMarkerCriticalColor + ","
        + "indicatorfadespeed:" + IndicatorFadeSpeed + ","
        + "indicatorcolor:" + IndicatorColor + ","
        + "loadingtextformat:" + LoadingTextFormat + ""
        + "}";
    }
}
}
