
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 内容解锁表
/// </summary>

public sealed partial class Unlock : Luban.BeanBase
{
    public Unlock(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        ContentType = (cfg.UnlockContentType)(int)_obj.GetValue("contentType");
        TargetId = (int)_obj.GetValue("targetId");
        RequirePlayerLevel = (int)_obj.GetValue("requirePlayerLevel");
        RequireCompleteLevelId = (int)_obj.GetValue("requireCompleteLevelId");
        CostGold = (int)_obj.GetValue("costGold");
        Comment = (string)_obj.GetValue("comment");
    }

    public static Unlock DeserializeUnlock(JToken _buf)
    {
        return new cfg.Unlock(_buf);
    }

    /// <summary>
    /// 解锁ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 内容类型
    /// </summary>
    public readonly cfg.UnlockContentType ContentType;
    /// <summary>
    /// 目标ID（关卡/武器）
    /// </summary>
    public readonly int TargetId;
    /// <summary>
    /// 要求玩家等级(0=无)
    /// </summary>
    public readonly int RequirePlayerLevel;
    /// <summary>
    /// 要求通关关卡ID(0=无)
    /// </summary>
    public readonly int RequireCompleteLevelId;
    /// <summary>
    /// 解锁花费金币(0=免费)
    /// </summary>
    public readonly int CostGold;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Comment;


    public const int __ID__ = 1877964846;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "contentType:" + ContentType + ","
        + "targetId:" + TargetId + ","
        + "requirePlayerLevel:" + RequirePlayerLevel + ","
        + "requireCompleteLevelId:" + RequireCompleteLevelId + ","
        + "costGold:" + CostGold + ","
        + "comment:" + Comment + ","
        + "}";
    }
}
}

