
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cfg
{ 
    /// <summary>
    /// 解锁内容类型
    /// </summary>
    public enum UnlockContentType
    {
        /// <summary>
        /// 关卡
        /// </summary>
        Level = 0,
        /// <summary>
        /// 武器
        /// </summary>
        Weapon = 1,
    }

} 

