
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 波次配置
/// </summary>

public sealed partial class Wave : Luban.BeanBase
{
    public Wave(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        LevelId = (int)_obj.GetValue("levelId");
        WaveIndex = (int)_obj.GetValue("waveIndex");
        EnemyId = (int)_obj.GetValue("enemyId");
        Count = (int)_obj.GetValue("count");
        SpawnInterval = (float)_obj.GetValue("spawnInterval");
        SpawnRadius = (float)_obj.GetValue("spawnRadius");
    }

    public static Wave DeserializeWave(JToken _buf)
    {
        return new cfg.Wave(_buf);
    }

    /// <summary>
    /// 波次ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly int LevelId;
    /// <summary>
    /// 波次索引
    /// </summary>
    public readonly int WaveIndex;
    /// <summary>
    /// 敌人ID
    /// </summary>
    public readonly int EnemyId;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 刷新间隔
    /// </summary>
    public readonly float SpawnInterval;
    /// <summary>
    /// 刷新半径
    /// </summary>
    public readonly float SpawnRadius;


    public const int __ID__ = -230400413;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelId:" + LevelId + ","
        + "waveIndex:" + WaveIndex + ","
        + "enemyId:" + EnemyId + ","
        + "count:" + Count + ","
        + "spawnInterval:" + SpawnInterval + ","
        + "spawnRadius:" + SpawnRadius + ","
        + "}";
    }
}
}

