
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cfg
{ 
    /// <summary>
    /// 武器类型
    /// </summary>
    public enum WeaponType
    {
        /// <summary>
        /// 手枪
        /// </summary>
        Pistol = 0,
        /// <summary>
        /// 冲锋枪
        /// </summary>
        SMG = 1,
        /// <summary>
        /// 步枪
        /// </summary>
        Rifle = 2,
        /// <summary>
        /// 狙击枪
        /// </summary>
        Sniper = 3,
        /// <summary>
        /// 火箭筒
        /// </summary>
        Rocket = 4,
    }

} 

