
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.cfg
{
/// <summary>
/// 武器配置
/// </summary>

public sealed partial class Weapon : Luban.BeanBase
{
    public Weapon(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        WeaponType = (cfg.WeaponType)(int)_obj.GetValue("weaponType");
        BallisticType = (cfg.BallisticType)(int)_obj.GetValue("ballisticType");
        FireMode = (cfg.FireMode)(int)_obj.GetValue("fireMode");
        Damage = (float)_obj.GetValue("damage");
        FireRate = (float)_obj.GetValue("fireRate");
        ClipSize = (int)_obj.GetValue("clipSize");
        ReloadTime = (float)_obj.GetValue("reloadTime");
        MaxRange = (float)_obj.GetValue("maxRange");
        BaseSpread = (float)_obj.GetValue("baseSpread");
        MoveSpreadMultiplier = (float)_obj.GetValue("moveSpreadMultiplier");
        FireSpreadIncrement = (float)_obj.GetValue("fireSpreadIncrement");
        SpreadRecoveryRate = (float)_obj.GetValue("spreadRecoveryRate");
        AimSpreadMultiplier = (float)_obj.GetValue("aimSpreadMultiplier");
        MoveSpeedMultiplier = (float)_obj.GetValue("moveSpeedMultiplier");
        FireMoveSpeedMultiplier = (float)_obj.GetValue("fireMoveSpeedMultiplier");
        AimFov = (float)_obj.GetValue("aimFov");
        AimSensitivityMultiplier = (float)_obj.GetValue("aimSensitivityMultiplier");
        AimAssistEnabled = (bool)_obj.GetValue("aimAssistEnabled");
        TracerSpeed = (float)_obj.GetValue("tracerSpeed");
        TracerDelay = (float)_obj.GetValue("tracerDelay");
        ProjectileSpeed = (float)_obj.GetValue("projectileSpeed");
        ProjectileLifeTime = (float)_obj.GetValue("projectileLifeTime");
        ProjectilePrefab = (string)_obj.GetValue("projectilePrefab");
        ExplosionRadius = (float)_obj.GetValue("explosionRadius");
        ExplosionDamageFalloff = (float)_obj.GetValue("explosionDamageFalloff");
        RecoilIntensity = (float)_obj.GetValue("recoilIntensity");
        RaycastRadius = (float)_obj.GetValue("raycastRadius");
        HitLayers = (string)_obj.GetValue("hitLayers");
        ShowDebugRay = (bool)_obj.GetValue("showDebugRay");
        DebugRayDuration = (float)_obj.GetValue("debugRayDuration");
        DebugHitColor = global::GameConfig.cfg.Color.DeserializeColor(_obj.GetValue("debugHitColor"));
        DebugMissColor = global::GameConfig.cfg.Color.DeserializeColor(_obj.GetValue("debugMissColor"));
        TrackingTime = (float)_obj.GetValue("trackingTime");
        TrackingLaserColor = global::GameConfig.cfg.Color.DeserializeColor(_obj.GetValue("trackingLaserColor"));
        LockOnSound = (string)_obj.GetValue("lockOnSound");
        MuzzleEffect = (string)_obj.GetValue("muzzleEffect");
        HitEffect = (string)_obj.GetValue("hitEffect");
        FireSound = (string)_obj.GetValue("fireSound");
        ReloadSound = (string)_obj.GetValue("reloadSound");
        AimAssistRadius = (float)_obj.GetValue("aimAssistRadius");
        AimAssistMaxAngle = (float)_obj.GetValue("aimAssistMaxAngle");
        LockOnRange = (float)_obj.GetValue("lockOnRange");
        LockOnAngle = (float)_obj.GetValue("lockOnAngle");
        LockOnHoldTime = (float)_obj.GetValue("lockOnHoldTime");
    }

    public static Weapon DeserializeWeapon(JToken _buf)
    {
        return new cfg.Weapon(_buf);
    }

    /// <summary>
    /// 武器ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 武器类型
    /// </summary>
    public readonly cfg.WeaponType WeaponType;
    /// <summary>
    /// 弹道类型
    /// </summary>
    public readonly cfg.BallisticType BallisticType;
    /// <summary>
    /// 开火模式
    /// </summary>
    public readonly cfg.FireMode FireMode;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly float Damage;
    /// <summary>
    /// 射速
    /// </summary>
    public readonly float FireRate;
    /// <summary>
    /// 弹匣容量
    /// </summary>
    public readonly int ClipSize;
    /// <summary>
    /// 换弹时间
    /// </summary>
    public readonly float ReloadTime;
    /// <summary>
    /// 最大射程
    /// </summary>
    public readonly float MaxRange;
    /// <summary>
    /// 基础扩散
    /// </summary>
    public readonly float BaseSpread;
    /// <summary>
    /// 移动扩散系数
    /// </summary>
    public readonly float MoveSpreadMultiplier;
    /// <summary>
    /// 开火扩散增量
    /// </summary>
    public readonly float FireSpreadIncrement;
    /// <summary>
    /// 扩散恢复速度
    /// </summary>
    public readonly float SpreadRecoveryRate;
    /// <summary>
    /// 瞄准扩散系数
    /// </summary>
    public readonly float AimSpreadMultiplier;
    /// <summary>
    /// 移动系数
    /// </summary>
    public readonly float MoveSpeedMultiplier;
    /// <summary>
    /// 开火移动系数
    /// </summary>
    public readonly float FireMoveSpeedMultiplier;
    /// <summary>
    /// 瞄准FOV
    /// </summary>
    public readonly float AimFov;
    /// <summary>
    /// 瞄准灵敏度系数
    /// </summary>
    public readonly float AimSensitivityMultiplier;
    /// <summary>
    /// 是否开启辅助瞄准
    /// </summary>
    public readonly bool AimAssistEnabled;
    /// <summary>
    /// 曳光速度
    /// </summary>
    public readonly float TracerSpeed;
    /// <summary>
    /// 曳光延迟
    /// </summary>
    public readonly float TracerDelay;
    /// <summary>
    /// 投掷物速度
    /// </summary>
    public readonly float ProjectileSpeed;
    /// <summary>
    /// 投掷物生命周期
    /// </summary>
    public readonly float ProjectileLifeTime;
    /// <summary>
    /// 投掷物Prefab
    /// </summary>
    public readonly string ProjectilePrefab;
    /// <summary>
    /// 爆炸半径
    /// </summary>
    public readonly float ExplosionRadius;
    /// <summary>
    /// 爆炸伤害衰减
    /// </summary>
    public readonly float ExplosionDamageFalloff;
    /// <summary>
    /// 后坐力强度
    /// </summary>
    public readonly float RecoilIntensity;
    /// <summary>
    /// 射线检测半径
    /// </summary>
    public readonly float RaycastRadius;
    /// <summary>
    /// 命中层级
    /// </summary>
    public readonly string HitLayers;
    /// <summary>
    /// 显示Debug射线
    /// </summary>
    public readonly bool ShowDebugRay;
    /// <summary>
    /// Debug射线持续时间
    /// </summary>
    public readonly float DebugRayDuration;
    /// <summary>
    /// Debug命中颜色
    /// </summary>
    public readonly cfg.Color DebugHitColor;
    /// <summary>
    /// Debug未命中颜色
    /// </summary>
    public readonly cfg.Color DebugMissColor;
    /// <summary>
    /// 锁定时间
    /// </summary>
    public readonly float TrackingTime;
    /// <summary>
    /// 锁定激光颜色
    /// </summary>
    public readonly cfg.Color TrackingLaserColor;
    /// <summary>
    /// 锁定音效
    /// </summary>
    public readonly string LockOnSound;
    /// <summary>
    /// 枪口特效
    /// </summary>
    public readonly string MuzzleEffect;
    /// <summary>
    /// 命中特效
    /// </summary>
    public readonly string HitEffect;
    /// <summary>
    /// 开火音效
    /// </summary>
    public readonly string FireSound;
    /// <summary>
    /// 换弹音效
    /// </summary>
    public readonly string ReloadSound;
    /// <summary>
    /// 2
    /// </summary>
    public readonly float AimAssistRadius;
    /// <summary>
    /// 15
    /// </summary>
    public readonly float AimAssistMaxAngle;
    /// <summary>
    /// 20
    /// </summary>
    public readonly float LockOnRange;
    /// <summary>
    /// 10
    /// </summary>
    public readonly float LockOnAngle;
    /// <summary>
    /// 1.5
    /// </summary>
    public readonly float LockOnHoldTime;


    public const int __ID__ = 1926585094;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        DebugHitColor?.ResolveRef(tables);
        DebugMissColor?.ResolveRef(tables);
        TrackingLaserColor?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "weapontype:" + WeaponType + ","
        + "ballistictype:" + BallisticType + ","
        + "firemode:" + FireMode + ","
        + "damage:" + Damage + ","
        + "firerate:" + FireRate + ","
        + "clipsize:" + ClipSize + ","
        + "reloadtime:" + ReloadTime + ","
        + "maxrange:" + MaxRange + ","
        + "basespread:" + BaseSpread + ","
        + "movespreadmultiplier:" + MoveSpreadMultiplier + ","
        + "firespreadincrement:" + FireSpreadIncrement + ","
        + "spreadrecoveryrate:" + SpreadRecoveryRate + ","
        + "aimspreadmultiplier:" + AimSpreadMultiplier + ","
        + "movespeedmultiplier:" + MoveSpeedMultiplier + ","
        + "firemovespeedmultiplier:" + FireMoveSpeedMultiplier + ","
        + "aimfov:" + AimFov + ","
        + "aimsensitivitymultiplier:" + AimSensitivityMultiplier + ","
        + "aimassistenabled:" + AimAssistEnabled + ","
        + "tracerspeed:" + TracerSpeed + ","
        + "tracerdelay:" + TracerDelay + ","
        + "projectilespeed:" + ProjectileSpeed + ","
        + "projectilelifetime:" + ProjectileLifeTime + ","
        + "projectileprefab:" + ProjectilePrefab + ","
        + "explosionradius:" + ExplosionRadius + ","
        + "explosiondamagefalloff:" + ExplosionDamageFalloff + ","
        + "recoilintensity:" + RecoilIntensity + ","
        + "raycastradius:" + RaycastRadius + ","
        + "hitlayers:" + HitLayers + ","
        + "showdebugray:" + ShowDebugRay + ","
        + "debugrayduration:" + DebugRayDuration + ","
        + "debughitcolor:" + DebugHitColor + ","
        + "debugmisscolor:" + DebugMissColor + ","
        + "trackingtime:" + TrackingTime + ","
        + "trackinglasercolor:" + TrackingLaserColor + ","
        + "lockonsound:" + LockOnSound + ","
        + "muzzleeffect:" + MuzzleEffect + ","
        + "hiteffect:" + HitEffect + ","
        + "firesound:" + FireSound + ","
        + "reloadsound:" + ReloadSound + ","
        + "aimassistradius:" + AimAssistRadius + ","
        + "aimassistmaxangle:" + AimAssistMaxAngle + ","
        + "lockonrange:" + LockOnRange + ","
        + "lockonangle:" + LockOnAngle + ","
        + "lockonholdtime:" + LockOnHoldTime + ""
        + "}";
    }
}
}
